"""Versioned registry for production agent output schema boundaries."""

from __future__ import annotations

from collections.abc import Mapping

from artana_evidence_api.runtime.agent_output_schema import (
    AgentOutputSchemaPolicy,
    AgentOutputSchemaRegistry,
    CategoryFieldPolicy,
    CategoryValuePolicy,
    NumericFieldPolicy,
)


def _category(
    path: str,
    definitions: Mapping[str, str],
    *,
    evidence_requirement: str,
    invalid_behavior: str = "Reject the model output and record an invalid response.",
    allow_schema_subset: bool = False,
    debt_id: str | None = None,
) -> CategoryFieldPolicy:
    return CategoryFieldPolicy(
        path=path,
        values=tuple(
            CategoryValuePolicy(
                value=value,
                definition=definition,
                positive_example=f"Use {value!r} only when {definition}",
                counterexample=f"Do not use {value!r} when that observable condition is absent.",
            )
            for value, definition in definitions.items()
        ),
        evidence_requirement=evidence_requirement,
        invalid_behavior=invalid_behavior,
        allow_schema_subset=allow_schema_subset,
        debt_id=debt_id,
    )


_SOURCE_TYPE = {
    "tool": "the cited evidence is a recorded tool result.",
    "db": "the cited evidence is a database record with a stable locator.",
    "paper": "the cited evidence is a paper span with a stable citation.",
    "web": "the cited evidence is a web resource with a stable URL.",
    "note": "the cited evidence is a user or workflow note with a stable locator.",
    "api": "the cited evidence is a recorded API response with a stable locator.",
}
_RUN_DECISION = {
    "generated": "the agent produced a schema-valid result from cited evidence.",
    "fallback": "the result came from an explicitly recorded non-agent fallback path.",
    "escalate": "missing or conflicting evidence requires human review.",
}
_FACT_SUPPORT = {
    "INSUFFICIENT": "no cited span establishes the asserted fact.",
    "TENTATIVE": "a cited span is indirect, incomplete, or explicitly uncertain.",
    "SUPPORTED": "a cited span directly establishes the asserted fact.",
    "STRONG": "multiple independent cited spans directly establish the same fact.",
}
_FACT_GROUNDING = {
    "SPAN": "the finding is anchored to one literal source span.",
    "SECTION": "the finding is anchored to a named source section but not one span.",
    "DOCUMENT": "the finding is supported only at whole-document scope.",
    "GENERATED": "the finding has no source anchor and was generated by the model.",
    "GRAPH_INFERENCE": "the finding follows from a cited graph path rather than source text.",
}
_FACT_SPECULATION = {
    "DIRECT": "the cited source states the fact without hedging.",
    "HEDGED": "the cited source explicitly hedges the fact.",
    "HYPOTHETICAL": "the cited source presents the fact as hypothetical.",
    "NOT_APPLICABLE": "speculation does not apply to this structured finding.",
}
_FACT_MAPPING = {
    "RESOLVED": "the cited entity or relation maps to one canonical identifier.",
    "AMBIGUOUS": "more than one canonical mapping remains possible.",
    "NOT_APPLICABLE": "the finding does not require canonical mapping.",
}
_GRAPH_SUPPORT = {
    "INSUFFICIENT": "no graph evidence item supports the result.",
    "TENTATIVE": "graph evidence is indirect or incomplete.",
    "SUPPORTED": "a relation or observation directly supports the result.",
    "STRONG": "multiple independent graph evidence items directly support the result.",
}
_GRAPH_GROUNDING = {
    "NONE": "the result has no entity, relation, or observation grounding.",
    "ENTITY": "the result is grounded only to a matching entity.",
    "RELATION": "the result is grounded to at least one relation.",
    "OBSERVATION": "the result is grounded to at least one observation.",
    "AGGREGATED": "the result is grounded to both relation and observation evidence.",
}
_ORCHESTRATOR_ACTION = {
    action: f"the deterministic action registry allows the {action} workflow at this checkpoint."
    for action in (
        "DERIVE_DRIVEN_TERMS",
        "ESCALATE_TO_HUMAN",
        "GENERATE_BRIEF",
        "INGEST_AND_EXTRACT_PUBMED",
        "INITIALIZE_WORKSPACE",
        "LOAD_MONDO_GROUNDING",
        "QUERY_PUBMED",
        "REVIEW_PDF_WORKSET",
        "REVIEW_TEXT_WORKSET",
        "RUN_BOOTSTRAP",
        "RUN_CHASE_ROUND",
        "RUN_GRAPH_CONNECTION",
        "RUN_GRAPH_SEARCH",
        "RUN_HGNC_GROUNDING",
        "RUN_HYPOTHESIS_GENERATION",
        "RUN_STRUCTURED_ENRICHMENT",
        "RUN_UNIPROT_GROUNDING",
        "SEARCH_DISCONFIRMING",
        "STOP",
    )
}


def _fact_categories(prefix: str) -> tuple[CategoryFieldPolicy, ...]:
    evidence = "The finding must include its source locator and supporting evidence."
    return (
        _category(
            f"{prefix}.support_band",
            _FACT_SUPPORT,
            evidence_requirement=evidence,
        ),
        _category(
            f"{prefix}.grounding_level",
            _FACT_GROUNDING,
            evidence_requirement=evidence,
        ),
        _category(
            f"{prefix}.speculation_level",
            _FACT_SPECULATION,
            evidence_requirement=evidence,
        ),
        _category(
            f"{prefix}.mapping_status",
            _FACT_MAPPING,
            evidence_requirement=evidence,
        ),
    )


def _graph_categories(prefix: str) -> tuple[CategoryFieldPolicy, ...]:
    evidence = "The category must be reproducible from the attached graph evidence IDs."
    return (
        _category(
            f"{prefix}.support_band",
            _GRAPH_SUPPORT,
            evidence_requirement=evidence,
        ),
        _category(
            f"{prefix}.grounding_level",
            _GRAPH_GROUNDING,
            evidence_requirement=evidence,
        ),
    )


_POLICIES = (
    AgentOutputSchemaPolicy(
        schema_id="evidence_selection.semantic.v1",
        schema_names=("EvidenceSelectionSemanticBatchContract",),
        shape_hash="9e5a7d2909d1cc98d129c0bbd51e470660d45aec89c0c300fc9eb40e5b85d33e",
        numeric_fields=(
            NumericFieldPolicy(
                path="$.assessments[].record_index",
                debt_id="AON-SEL-001",
            ),
        ),
        categorical_fields=(
            _category(
                "$.schema_version",
                {
                    "evidence_selection_semantic_agent.v1": (
                        "the payload follows semantic selector schema version 1."
                    ),
                },
                evidence_requirement="This is a fixed protocol marker.",
            ),
            _category(
                "$.assessments[].decision",
                {
                    "select": "all required criteria are supported and no exclusion is triggered.",
                    "reject": "a required criterion is contradicted or an exclusion is triggered.",
                    "review": "the available source text cannot resolve a required criterion.",
                },
                evidence_requirement="Every decision must cite the complete criterion findings.",
            ),
            _category(
                "$.assessments[].objective_match",
                {
                    "direct": "the record directly answers the stated research objective.",
                    "supporting": "the record supplies evidence needed to answer the objective.",
                    "context_only": "the record supplies background but no answer evidence.",
                    "off_objective": "the record addresses a different question.",
                    "uncertain": "the supplied text cannot establish objective alignment.",
                },
                evidence_requirement="A cited title or abstract span must establish the category.",
            ),
            *(
                _category(
                    f"$.assessments[].{field_name}",
                    {
                        "match": f"the cited record explicitly satisfies {label}.",
                        "no_match": f"the cited record explicitly contradicts {label}.",
                        "not_required": f"the research objective does not require {label}.",
                        "uncertain": f"the supplied record does not resolve {label}.",
                    },
                    evidence_requirement="A literal cited span or explicit missing-information finding is required.",
                )
                for field_name, label in (
                    ("entity_variant_match", "the requested entity or variant"),
                    ("population_match", "the requested population"),
                    ("intervention_match", "the requested intervention"),
                    ("outcome_match", "the requested outcome"),
                    ("study_type_match", "the requested study type"),
                )
            ),
            _category(
                "$.assessments[].inclusion_assessment",
                {
                    "met": "every inclusion criterion has direct supporting evidence.",
                    "not_met": "at least one inclusion criterion is contradicted.",
                    "uncertain": "at least one inclusion criterion lacks enough evidence.",
                },
                evidence_requirement="Criterion-level findings and cited spans are required.",
            ),
            _category(
                "$.assessments[].exclusion_assessment",
                {
                    "not_triggered": "no exclusion criterion is supported by the cited record.",
                    "triggered": "at least one exclusion criterion is directly supported.",
                    "uncertain": "the record cannot resolve at least one applicable exclusion.",
                },
                evidence_requirement="Criterion-level findings and cited spans are required.",
            ),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="evidence_selection.source_plan.v1",
        schema_names=("ModelEvidenceSelectionSourcePlanContract",),
        shape_hash="231f5fe113d25ee0544447ecedf445747c22939bf440a9eda1e3c90f05161d74",
        numeric_fields=(
            NumericFieldPolicy(
                path="$.planned_searches[].max_records",
                debt_id="AON-PLAN-001",
            ),
            NumericFieldPolicy(
                path="$.planned_searches[].taxon_id",
                debt_id="AON-PLAN-002",
            ),
            NumericFieldPolicy(
                path="$.planned_searches[].timeout_seconds",
                debt_id="AON-PLAN-003",
            ),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="graph_connection.agent.v1",
        schema_names=("_GraphConnectionExecutionContract",),
        shape_hash="67e9edc4e85b747cd93c6f0cc8b864d01d0fb21c75cdb97ae7416d0b561a58c5",
        numeric_fields=(
            NumericFieldPolicy(path="$.confidence_score", debt_id="AON-GCON-001"),
            NumericFieldPolicy(path="$.evidence[].relevance", debt_id="AON-SHARED-002"),
            NumericFieldPolicy(path="$.proposed_relations[].confidence", debt_id="AON-GCON-002"),
            NumericFieldPolicy(
                path="$.proposed_relations[].supporting_document_count",
                debt_id="AON-GCON-003",
            ),
            NumericFieldPolicy(path="$.rejected_candidates[].confidence", debt_id="AON-GCON-004"),
        ),
        categorical_fields=(
            _category("$.decision", _RUN_DECISION, evidence_requirement="The executed path and run ID are required."),
            _category("$.evidence[].source_type", _SOURCE_TYPE, evidence_requirement="Every item requires a stable locator."),
            _category("$.proposed_relations[].evidence_tier", {"COMPUTATIONAL": "the relation is model-generated and not trusted evidence."}, evidence_requirement="The agent run ID is required."),
            *_fact_categories("$.proposed_relations[].assessment"),
            *_fact_categories("$.rejected_candidates[].assessment"),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="graph_search.agent.v1",
        schema_names=("_GraphSearchExecutionContract",),
        shape_hash="044bf94a38499e6f0dafd6d4e7b1ccd05d2010d612d832a26e70c4713724bf6f",
        numeric_fields=(
            NumericFieldPolicy(path="$.confidence_score", debt_id="AON-GSEA-001"),
            NumericFieldPolicy(path="$.evidence[].relevance", debt_id="AON-SHARED-002"),
            NumericFieldPolicy(path="$.results[].evidence_chain[].confidence", debt_id="AON-GSEA-002"),
            NumericFieldPolicy(path="$.results[].relevance_score", debt_id="AON-GSEA-003"),
            NumericFieldPolicy(path="$.total_results", debt_id="AON-GSEA-004"),
        ),
        categorical_fields=(
            _category("$.decision", _RUN_DECISION, evidence_requirement="The executed path and run ID are required."),
            _category("$.evidence[].source_type", _SOURCE_TYPE, evidence_requirement="Every item requires a stable locator."),
            _category("$.executed_path", {"deterministic": "the result used only deterministic execution.", "agent": "the model agent produced the result.", "agent_fallback": "the agent failed and an explicit fallback produced the result."}, evidence_requirement="Runtime provenance must establish the path."),
            *_graph_categories("$.assessment"),
            *_graph_categories("$.results[].assessment"),
            *_graph_categories("$.results[].evidence_chain[].assessment"),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="research_onboarding.agent.v1",
        schema_names=("OnboardingAssistantContract",),
        shape_hash="d7f808ea5d835f87372df00b0f3543470fc697e3e6d69037823b82115fe52a6b",
        numeric_fields=(
            NumericFieldPolicy(path="$.confidence_score", debt_id="AON-SHARED-001"),
            NumericFieldPolicy(path="$.evidence[].relevance", debt_id="AON-SHARED-002"),
            NumericFieldPolicy(path="$.state_patch.pending_question_count", debt_id="AON-ONBD-001"),
        ),
        categorical_fields=(
            _category("$.evidence[].source_type", _SOURCE_TYPE, evidence_requirement="Every item requires a stable locator."),
            _category("$.message_type", {"clarification_request": "a required research input is still missing.", "plan_ready": "all required onboarding inputs are present."}, evidence_requirement="The state patch and rationale must identify the condition."),
            _category("$.state_patch.onboarding_status", {"awaiting_researcher_reply": "the workflow requires a researcher response.", "plan_ready": "the workflow has enough input to build the plan."}, evidence_requirement="The pending questions must establish the status."),
            _category("$.state_patch.thread_status", {"your_turn": "the researcher must answer a question.", "review_needed": "the researcher must review a completed plan."}, evidence_requirement="The suggested action must establish the status."),
            _category("$.suggested_actions[].action_type", {"reply": "the next action is a researcher response.", "review": "the next action is review of generated work."}, evidence_requirement="The corresponding action payload is required."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="pubmed.relevance.v1",
        schema_names=("PubMedRelevanceContract",),
        shape_hash="f93a152862754dc9ef0f25da8d58cd7dfb04a1965eaa25a975cd3ba83aed8654",
        numeric_fields=(
            NumericFieldPolicy(path="$.confidence_score", debt_id="AON-SHARED-001"),
            NumericFieldPolicy(path="$.evidence[].relevance", debt_id="AON-SHARED-002"),
        ),
        categorical_fields=(
            _category("$.evidence[].source_type", _SOURCE_TYPE, evidence_requirement="Every item requires a stable locator."),
            _category("$.relevance", {"relevant": "the title or abstract directly addresses the supplied research context.", "non_relevant": "the title and abstract do not address the supplied research context."}, evidence_requirement="A literal title or abstract span is required."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="relation_type_resolution.agent.v1",
        schema_names=("RelationTypeDecision",),
        shape_hash="4ae532517c388aa19610e41bbfa6ae129e11a3251a6b53a00ba671b1ba6b8f78",
        categorical_fields=(
            _category("$.action", {"map_to_existing": "one existing canonical relation has the same semantics.", "register_new": "no canonical relation covers the supported semantics.", "requires_review": "the available context cannot resolve the mapping safely.", "typo_correction": "the input differs from one canonical relation only by a demonstrable typo."}, evidence_requirement="The rationale must cite the candidate taxonomy entries."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="entity_resolution.agent.v1",
        schema_names=("EntityDecision",),
        shape_hash="1f930649a4bbc34b39bd204d05073fd27db6d8b5de88c9cda5050c7ac0d3835c",
        categorical_fields=(
            _category("$.action", {"match_existing": "one existing entity uniquely matches the supplied label and anchors.", "create_new": "no existing entity matches the supplied label and anchors."}, evidence_requirement="The rationale must cite candidate entities and supplied anchors."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="marrvel.gene_inference.v1",
        schema_names=("_MarrvelGeneInferenceResult",),
        shape_hash="e36df65cd58006ebeef2350b47cc09662baa1ae957e17d1001fe64a0204a7d5e",
    ),
    AgentOutputSchemaPolicy(
        schema_id="document_extraction.relation.v2",
        schema_names=("LLMExtractionResult",),
        shape_hash="53bd185c9ca1906c8bad89ff584e2dd623b7ce49b3a1b2485c42f2fe1e8abc11",
        categorical_fields=(
            _category("$.relations[].review_status", {"candidate": "the cited sentence directly supports a canonical relation candidate.", "review_only": "the cited sentence is weak, hedged, or requires human interpretation."}, evidence_requirement="The literal source sentence is required."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="document_extraction.proposal_review.v1",
        schema_names=("ProposalReviewResult",),
        shape_hash="2e7f22a9f032f64fb1e9dc0135fa812478246ca08a4ede16f211cc36c8e66d13",
        numeric_fields=(
            NumericFieldPolicy(path="$.reviews[].index", debt_id="AON-PROP-001"),
        ),
        categorical_fields=(
            _category("$.reviews[].factual_support", {"strong": "multiple direct source spans support the proposal.", "moderate": "one direct source span supports the proposal.", "tentative": "the source is hedged or indirect.", "unsupported": "no cited source span supports the proposal."}, evidence_requirement="A factual rationale tied to source text is required."),
            _category("$.reviews[].goal_relevance", {"direct": "the proposal directly answers the research goal.", "supporting": "the proposal supports an answer to the goal.", "peripheral": "the proposal is related background only.", "off_target": "the proposal addresses a different goal.", "unscoped": "the supplied goal is insufficient to classify relevance."}, evidence_requirement="A relevance rationale tied to the goal is required."),
            _category("$.reviews[].priority", {"prioritize": "direct supported evidence requires immediate review.", "review": "supported evidence should enter normal review.", "background": "the proposal is context only.", "ignore": "the proposal is unsupported or off target."}, evidence_requirement="The factual-support and goal-relevance categories must deterministically permit this value."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="model_health.probe.v1",
        schema_names=("_ProbeOutput",),
        shape_hash="53ceee97278087ef366f8a0a8399cfab1b60ca83917bf20b3e1063310fe9fce4",
        categorical_fields=(
            _category("$.status", {"ok": "the provider returned the exact structured health response."}, evidence_requirement="This is a fixed transport-health protocol marker."),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="variant_extraction.agent.v1",
        schema_names=("LLMExtractionContract",),
        shape_hash="20a4d0de30915f883b49eda5bea51d1734a566b6bfd09a8c6e0a60ceb4b0d8c3",
        numeric_fields=(
            NumericFieldPolicy(path="$.confidence_score", debt_id="AON-VEXT-001"),
            NumericFieldPolicy(path="$.evidence[].relevance", debt_id="AON-SHARED-002"),
            *(
                NumericFieldPolicy(path=path, debt_id=debt_id)
                for path, debt_id in (
                    ("$.entities[].anchors[].value", "AON-VEXT-002"),
                    ("$.entities[].metadata[].value", "AON-VEXT-003"),
                    ("$.observations[].value", "AON-VEXT-004"),
                    ("$.rejected_facts[].payload[].value", "AON-VEXT-005"),
                    ("$.relations[].source_anchors[].value", "AON-VEXT-006"),
                    ("$.relations[].target_anchors[].value", "AON-VEXT-007"),
                )
            ),
        ),
        categorical_fields=(
            _category("$.decision", _RUN_DECISION, evidence_requirement="The executed path and run ID are required."),
            _category("$.evidence[].source_type", _SOURCE_TYPE, evidence_requirement="Every item requires a stable locator."),
            _category("$.rejected_facts[].fact_type", {"observation": "the rejected candidate is an observation.", "relation": "the rejected candidate is a relation."}, evidence_requirement="The rejected payload and reason are required."),
            _category("$.relations[].polarity", {"SUPPORT": "the cited source supports the relation.", "REFUTE": "the cited source contradicts the relation.", "UNCERTAIN": "the cited source is ambiguous or hedged.", "HYPOTHESIS": "the cited source presents the relation as hypothetical."}, evidence_requirement="A literal evidence span and locator are required."),
            *(
                category
                for prefix in (
                    "$.entities[].assessment",
                    "$.observations[].assessment",
                    "$.relations[].assessment",
                    "$.rejected_facts[].assessment",
                )
                for category in _fact_categories(prefix)
            ),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="full_ai.shadow_planner.v1",
        schema_names=(
            "ShadowPlannerLiveRecommendationOutput",
            "ShadowPlannerRecommendationOutput",
        ),
        shape_hash="6aa85f6fb20a2697c75c0d99f33d6b14bb553023a8066b177d72cb2306e5039d",
        categorical_fields=(
            _category(
                "$.action_type",
                _ORCHESTRATOR_ACTION,
                evidence_requirement=(
                    "The action must be present in the deterministic checkpoint action registry."
                ),
                allow_schema_subset=True,
            ),
            _category(
                "$.expected_value_band",
                {
                    "low": "the agent predicts limited workflow value.",
                    "medium": "the agent predicts intermediate workflow value.",
                    "high": "the agent predicts substantial workflow value.",
                },
                evidence_requirement="The qualitative rationale currently supplies the basis.",
                debt_id="AOC-SHADOW-001",
            ),
            _category(
                "$.risk_level",
                {
                    "low": "the agent predicts limited workflow risk.",
                    "medium": "the agent predicts intermediate workflow risk.",
                    "high": "the agent predicts substantial workflow risk.",
                },
                evidence_requirement="The qualitative rationale currently supplies the basis.",
                debt_id="AOC-SHADOW-002",
            ),
        ),
    ),
    AgentOutputSchemaPolicy(
        schema_id="research.brief.v1",
        schema_names=("LLMBriefOutput",),
        shape_hash="9c7621ed9f2066c3bc01806be1f8946caff0dcb1c6445db460431d91a8e5c019",
    ),
)

AGENT_OUTPUT_SCHEMA_REGISTRY = AgentOutputSchemaRegistry(_POLICIES)


def validate_registered_agent_output_schema(
    *,
    schema_id: str,
    output_schema: type[object],
) -> AgentOutputSchemaPolicy:
    """Validate a production model-output boundary against the registry."""

    return AGENT_OUTPUT_SCHEMA_REGISTRY.validate(
        schema_id=schema_id,
        output_schema=output_schema,
    )


__all__ = [
    "AGENT_OUTPUT_SCHEMA_REGISTRY",
    "validate_registered_agent_output_schema",
]
