// Auto-generated by scripts/generate_ts_types.py. Do not edit.
/* eslint-disable */
/* prettier-ignore */

export type JSONValue = string | number | boolean | null | JSONArray | JSONObject;
export type JSONObject = { [key: string]: JSONValue };
export type JSONArray = JSONValue[];

export interface AIDecisionListResponse {
  ai_decisions: AIDecisionResponse[];
  total: number;
}

export interface AIDecisionResponse {
  id: string;
  research_space_id: string;
  target_type: 'concept_proposal' | 'graph_change_proposal';
  target_id: string;
  action: 'APPLY_RESOLUTION_PLAN' | 'APPROVE' | 'MERGE' | 'REJECT' | 'REQUEST_CHANGES';
  status: 'APPLIED' | 'REJECTED' | 'SUBMITTED';
  ai_principal: string;
  confidence: number;
  computed_confidence: number;
  confidence_assessment_payload: Record<string, unknown>;
  confidence_model_version: string | null;
  risk_tier: 'high' | 'low' | 'medium';
  input_hash: string;
  policy_outcome: 'ai_allowed' | 'ai_allowed_when_low_risk' | 'blocked' | 'human_required';
  evidence_payload: Record<string, unknown>;
  decision_payload: Record<string, unknown>;
  rejection_reason: string | null;
  created_by: string;
  applied_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface AIDecisionSubmitRequest {
  target_type: 'concept_proposal' | 'graph_change_proposal';
  target_id: string;
  action: 'APPLY_RESOLUTION_PLAN' | 'APPROVE' | 'MERGE' | 'REJECT' | 'REQUEST_CHANGES';
  ai_principal: string;
  confidence_assessment: DecisionConfidenceAssessment;
  risk_tier: 'high' | 'low' | 'medium';
  input_hash: string;
  evidence_payload?: Record<string, unknown>;
  decision_payload?: Record<string, unknown>;
}

export interface ClaimAIProvenanceEnvelope {
  model_id: string;
  model_version: string;
  prompt_id: string;
  prompt_version: string;
  input_hash: string;
  rationale: string;
  evidence_references?: string[];
  tool_trace_ref?: string | null;
}

export interface ClaimParticipantBackfillRequest {
  dry_run?: boolean;
  limit?: number;
  offset?: number;
}

export interface ClaimParticipantBackfillResponse {
  operation_run_id: string;
  scanned_claims: number;
  created_participants: number;
  skipped_existing: number;
  unresolved_endpoints: number;
  dry_run: boolean;
}

export interface ClaimParticipantCoverageResponse {
  total_claims: number;
  claims_with_any_participants: number;
  claims_with_subject: number;
  claims_with_object: number;
  unresolved_subject_endpoints: number;
  unresolved_object_endpoints: number;
  unresolved_endpoint_rate: number;
}

export interface ClaimParticipantListResponse {
  claim_id: string;
  participants: ClaimParticipantResponse[];
  total: number;
}

export interface ClaimParticipantResponse {
  id: string;
  claim_id: string;
  research_space_id: string;
  label: string | null;
  entity_id: string | null;
  role: string;
  position: number | null;
  qualifiers: Record<string, unknown>;
  created_at: string;
}

export interface ClaimRelationCreateRequest {
  source_claim_id: string;
  target_claim_id: string;
  relation_type: string;
  agent_run_id?: string | null;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  assessment: FactAssessment;
  review_status?: string;
  evidence_summary?: string | null;
  metadata?: Record<string, unknown>;
}

export interface ClaimRelationListResponse {
  claim_relations: ClaimRelationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface ClaimRelationResponse {
  id: string;
  research_space_id: string;
  source_claim_id: string;
  target_claim_id: string;
  relation_type: string;
  agent_run_id: string | null;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  confidence: number;
  review_status: string;
  evidence_summary: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface ClaimRelationReviewUpdateRequest {
  review_status: string;
}

export interface ConceptAliasListResponse {
  concept_aliases: ConceptAliasResponse[];
  total: number;
}

export interface ConceptAliasResponse {
  id: number;
  concept_member_id: string;
  research_space_id: string;
  domain_context: string;
  alias_label: string;
  alias_normalized: string;
  source: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptDecisionListResponse {
  concept_decisions: ConceptDecisionResponse[];
  total: number;
}

export interface ConceptDecisionResponse {
  id: string;
  research_space_id: string;
  concept_set_id: string | null;
  concept_member_id: string | null;
  concept_link_id: string | null;
  decision_type: 'CREATE' | 'DEMOTE' | 'LINK' | 'MAP' | 'MERGE' | 'PROMOTE' | 'SPLIT';
  decision_status: 'APPLIED' | 'APPROVED' | 'NEEDS_REVIEW' | 'PROPOSED' | 'REJECTED';
  proposed_by: string;
  decided_by: string | null;
  confidence: number | null;
  rationale: string | null;
  evidence_payload: Record<string, unknown>;
  decision_payload: Record<string, unknown>;
  harness_outcome: 'FAIL' | 'NEEDS_REVIEW' | 'PASS' | null;
  decided_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptDecisionStatusRequest {
  decision_status: 'APPLIED' | 'APPROVED' | 'NEEDS_REVIEW' | 'PROPOSED' | 'REJECTED';
}

export interface ConceptExternalRefRequest {
  namespace: string;
  identifier: string;
}

export interface ConceptMemberListResponse {
  concept_members: ConceptMemberResponse[];
  total: number;
}

export interface ConceptMemberResponse {
  id: string;
  concept_set_id: string;
  research_space_id: string;
  domain_context: string;
  canonical_label: string;
  normalized_label: string;
  sense_key: string;
  dictionary_dimension: string | null;
  dictionary_entry_id: string | null;
  is_provisional: boolean;
  metadata_payload: Record<string, unknown>;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptPolicyResponse {
  id: string;
  research_space_id: string;
  profile_name: string;
  mode: 'BALANCED' | 'DISCOVERY' | 'PRECISION';
  minimum_edge_confidence: number;
  minimum_distinct_documents: number;
  allow_generic_relations: boolean;
  max_edges_per_document: number | null;
  policy_payload: Record<string, unknown>;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConceptProposalCreateRequest {
  domain_context: string;
  entity_type: string;
  canonical_label: string;
  synonyms?: string[];
  external_refs?: ConceptExternalRefRequest[];
  evidence_payload?: Record<string, unknown>;
  rationale?: string | null;
  source_ref?: string | null;
}

export interface ConceptProposalDecisionRequest {
  decision_reason?: string | null;
}

export interface ConceptProposalListResponse {
  concept_proposals: ConceptProposalResponse[];
  total: number;
}

export interface ConceptProposalMergeRequest {
  target_concept_member_id: string;
  decision_reason?: string | null;
}

export interface ConceptProposalRejectRequest {
  decision_reason: string;
}

export interface ConceptProposalResponse {
  id: string;
  research_space_id: string;
  status: 'APPLIED' | 'APPROVED' | 'CHANGES_REQUESTED' | 'DUPLICATE_CANDIDATE' | 'MERGED' | 'REJECTED' | 'SUBMITTED';
  candidate_decision: 'CREATE_NEW' | 'EXTERNAL_REF_MATCH' | 'MATCH_EXISTING' | 'MERGE_AS_SYNONYM' | 'NEEDS_REVIEW' | 'SYNONYM_COLLISION';
  domain_context: string;
  entity_type: string;
  canonical_label: string;
  normalized_label: string;
  concept_set_id: string | null;
  existing_concept_member_id: string | null;
  applied_concept_member_id: string | null;
  synonyms_payload: string[];
  external_refs_payload: Record<string, unknown>[];
  evidence_payload: Record<string, unknown>;
  duplicate_checks_payload: Record<string, unknown>;
  warnings_payload: string[];
  decision_payload: Record<string, unknown>;
  rationale: string | null;
  proposed_by: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
  decision_reason: string | null;
  source_ref: string | null;
  proposal_hash: string;
  created_at: string;
  updated_at: string;
}

export interface ConceptSetListResponse {
  concept_sets: ConceptSetResponse[];
  total: number;
}

export interface ConceptSetResponse {
  id: string;
  research_space_id: string;
  name: string;
  slug: string;
  domain_context: string;
  description: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConnectorProposalCreateRequest {
  connector_slug: string;
  display_name: string;
  connector_kind: string;
  domain_context: string;
  metadata_payload?: Record<string, unknown>;
  mapping_payload?: Record<string, unknown>;
  evidence_payload?: Record<string, unknown>;
  rationale?: string | null;
  source_ref?: string | null;
}

export interface ConnectorProposalListResponse {
  connector_proposals: ConnectorProposalResponse[];
  total: number;
}

export interface ConnectorProposalResponse {
  id: string;
  research_space_id: string;
  status: 'APPROVED' | 'CHANGES_REQUESTED' | 'REJECTED' | 'SUBMITTED';
  connector_slug: string;
  display_name: string;
  connector_kind: string;
  domain_context: string;
  metadata_payload: Record<string, unknown>;
  mapping_payload: Record<string, unknown>;
  validation_payload: Record<string, unknown>;
  approval_payload: Record<string, unknown>;
  rationale: string | null;
  evidence_payload: Record<string, unknown>;
  proposed_by: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
  decision_reason: string | null;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateManualHypothesisRequest {
  statement: string;
  rationale: string;
  seed_entity_ids?: string[];
  source_type?: string;
}

export interface DecisionConfidenceAssessment {
  fact_assessment: FactAssessment;
  validation_state?: 'INVALID' | 'REVIEW_REQUIRED' | 'VALID' | 'VALID_WITH_GRAPH_REPAIR';
  evidence_state?: 'ACCEPTED_DIRECT_EVIDENCE' | 'DIRECT_EVIDENCE_PRESENT' | 'EVIDENCE_LOCATOR_ONLY' | 'GENERATED_SUMMARY_ONLY' | 'REQUIRED_EVIDENCE_MISSING';
  duplicate_conflict_state?: 'CLEAR' | 'CONFLICTING_CLAIM' | 'DUPLICATE_EXISTING' | 'POSSIBLE_DUPLICATE';
  source_reliability?: 'AI_GENERATED_ONLY' | 'CURATED' | 'TRUSTED_EXTERNAL' | 'UNKNOWN' | 'USER_UPLOADED';
  risk_tier?: 'high' | 'low' | 'medium';
  rationale?: string | null;
}

export interface DecisionConfidenceResult {
  confidence_model_version: string;
  computed_confidence: number;
  cap_values: Record<string, number>;
  blocking_reasons: string[];
  human_review_reasons: string[];
}

export interface DictionaryChangelogListResponse {
  changelog_entries: DictionaryChangelogResponse[];
  total: number;
}

export interface DictionaryChangelogResponse {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  before_snapshot: Record<string, unknown> | null;
  after_snapshot: Record<string, unknown> | null;
  changed_by: string | null;
  source_ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryDomainContextListResponse {
  domain_contexts: DictionaryDomainContextResponse[];
  total: number;
}

export interface DictionaryDomainContextResponse {
  id: string;
  display_name: string;
  description: string | null;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryEntityTypeCreateRequest {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  external_ontology_ref?: string | null;
  expected_properties?: Record<string, unknown>;
  source_ref?: string | null;
}

export interface DictionaryEntityTypeListResponse {
  entity_types: DictionaryEntityTypeResponse[];
  total: number;
}

export interface DictionaryEntityTypeResponse {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  external_ontology_ref: string | null;
  expected_properties: Record<string, unknown>;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryEntityTypeValidationRequest {
  entity_type: string;
}

export interface DictionaryMergeRequest {
  target_id: string;
  reason: string;
}

export interface DictionaryReembedRequest {
  model_name?: string | null;
  limit_per_dimension?: number | null;
  source_ref?: string | null;
}

export interface DictionaryReembedResponse {
  updated_records: number;
  model_name: string | null;
}

export interface DictionaryRelationConstraintValidationRequest {
  source_type: string;
  relation_type: string;
  target_type: string;
  has_evidence?: boolean;
}

export interface DictionaryRelationSynonymCreateRequest {
  relation_type_id: string;
  synonym: string;
  source?: string | null;
  source_ref?: string | null;
}

export interface DictionaryRelationSynonymListResponse {
  relation_synonyms: DictionaryRelationSynonymResponse[];
  total: number;
}

export interface DictionaryRelationSynonymResponse {
  id: number;
  relation_type: string;
  synonym: string;
  source: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryRelationTypeCreateRequest {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  is_directional?: boolean;
  inverse_label?: string | null;
  source_ref?: string | null;
}

export interface DictionaryRelationTypeListResponse {
  relation_types: DictionaryRelationTypeResponse[];
  total: number;
}

export interface DictionaryRelationTypeResponse {
  id: string;
  display_name: string;
  description: string;
  domain_context: string;
  is_directional: boolean;
  inverse_label: string | null;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface DictionaryRelationTypeValidationRequest {
  relation_type: string;
}

export interface DictionarySearchListResponse {
  results: DictionarySearchResultResponse[];
  total: number;
}

export interface DictionarySearchResultResponse {
  dimension: 'variables' | 'entity_types' | 'relation_types' | 'constraints';
  entry_id: string;
  display_name: string;
  description: string | null;
  domain_context: string | null;
  match_method: 'exact' | 'synonym' | 'fuzzy' | 'vector';
  similarity_score: number;
  metadata: Record<string, unknown>;
}

export interface EntityResolutionPolicyListResponse {
  policies: EntityResolutionPolicyResponse[];
  total: number;
}

export interface EntityResolutionPolicyResponse {
  entity_type: string;
  policy_strategy: string;
  required_anchors: string[];
  auto_merge_threshold: number;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ExplanationResponse {
  research_space_id: string;
  resource_type: string;
  resource_id: string;
  why_this_exists: string;
  approved_by?: string | null;
  evidence?: Record<string, unknown>;
  policy?: Record<string, unknown>;
  generated_resources?: Record<string, unknown>;
  validation?: Record<string, unknown>;
  next_action?: Record<string, unknown>;
  details?: Record<string, unknown>;
}

export interface FactAssessment {
  support_band: 'INSUFFICIENT' | 'TENTATIVE' | 'SUPPORTED' | 'STRONG';
  grounding_level: 'SPAN' | 'SECTION' | 'DOCUMENT' | 'GENERATED' | 'GRAPH_INFERENCE';
  mapping_status: 'RESOLVED' | 'AMBIGUOUS' | 'NOT_APPLICABLE';
  speculation_level: 'DIRECT' | 'HEDGED' | 'HYPOTHETICAL' | 'NOT_APPLICABLE';
  confidence_rationale: string;
}

export interface GenerateHypothesesRequest {
  seed_entity_ids?: string[] | null;
  source_type?: string;
  relation_types?: string[] | null;
  max_depth?: number;
  max_hypotheses?: number;
  model_id?: string | null;
}

export interface GenerateHypothesesResponse {
  run_id: string;
  requested_seed_count: number;
  used_seed_count: number;
  candidates_seen: number;
  created_count: number;
  deduped_count: number;
  errors: string[];
  hypotheses: HypothesisResponse[];
}

export interface GraphChangeClaimRequest {
  source_local_id: string;
  target_local_id: string;
  relation_type: string;
  assessment: FactAssessment;
  evidence_payload?: Record<string, unknown>;
  claim_text?: string | null;
  source_document_ref?: string | null;
}

export interface GraphChangeConceptRequest {
  local_id: string;
  domain_context: string;
  entity_type: string;
  canonical_label: string;
  synonyms?: string[];
  external_refs?: ConceptExternalRefRequest[];
  evidence_payload?: Record<string, unknown>;
  rationale?: string | null;
}

export interface GraphChangeProposalCreateRequest {
  concepts: GraphChangeConceptRequest[];
  claims?: GraphChangeClaimRequest[];
  source_ref?: string | null;
}

export interface GraphChangeProposalListResponse {
  graph_change_proposals: GraphChangeProposalResponse[];
  total: number;
}

export interface GraphChangeProposalResponse {
  id: string;
  research_space_id: string;
  status: 'APPLIED' | 'CHANGES_REQUESTED' | 'READY_FOR_REVIEW' | 'REJECTED';
  proposal_payload: Record<string, unknown>;
  resolution_plan_payload: Record<string, unknown>;
  warnings_payload: string[];
  error_payload: string[];
  applied_concept_member_ids_payload: string[];
  applied_claim_ids_payload: string[];
  proposed_by: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
  decision_reason: string | null;
  source_ref: string | null;
  proposal_hash: string;
  created_at: string;
  updated_at: string;
}

export interface GraphDomainPackListResponse {
  active_pack: string;
  packs: GraphDomainPackSummaryResponse[];
}

export interface GraphDomainPackSummaryResponse {
  name: string;
  version: string;
  service_name: string;
  jwt_issuer: string;
  domain_contexts: string[];
  entity_types: string[];
  relation_types: string[];
  agent_capabilities: Record<string, string[]>;
}

export interface GraphPackSeedOperationResponse {
  applied: boolean;
  operation: 'repair' | 'seed';
  status: GraphPackSeedStatusResponse;
}

export interface GraphPackSeedStatusResponse {
  id: string;
  research_space_id: string;
  pack_name: string;
  pack_version: string;
  status: string;
  last_operation: string;
  seed_count: number;
  repair_count: number;
  metadata?: Record<string, unknown>;
  seeded_at: string;
  repaired_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface GraphValidationNextAction {
  action: string;
  reason: string;
  proposal_type?: string | null;
  endpoint?: string | null;
  payload?: Record<string, unknown>;
}

export interface GraphWorkflowActionRequest {
  action: 'apply_plan' | 'approve' | 'defer_to_human' | 'mark_resolved' | 'reject' | 'request_changes' | 'split';
  input_hash?: string | null;
  risk_tier?: 'high' | 'low' | 'medium';
  confidence_assessment?: DecisionConfidenceAssessment | null;
  reason?: string | null;
  decision_payload?: Record<string, unknown>;
  generated_resources_payload?: Record<string, unknown>;
  ai_decision?: GraphWorkflowAIDecisionEnvelope | null;
}

export interface GraphWorkflowCreateRequest {
  kind: 'ai_evidence_decision' | 'batch_review' | 'bootstrap_review' | 'conflict_resolution' | 'continuous_learning_review' | 'evidence_approval';
  input_payload?: Record<string, unknown>;
  decision_payload?: Record<string, unknown>;
  source_ref?: string | null;
}

export interface GraphWorkflowListResponse {
  workflows: GraphWorkflowResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface GraphWorkflowResponse {
  id: string;
  research_space_id: string;
  kind: 'ai_evidence_decision' | 'batch_review' | 'bootstrap_review' | 'conflict_resolution' | 'continuous_learning_review' | 'evidence_approval';
  status: 'APPLIED' | 'BLOCKED' | 'CHANGES_REQUESTED' | 'FAILED' | 'PLAN_READY' | 'REJECTED' | 'SUBMITTED' | 'WAITING_REVIEW';
  operating_mode: 'ai_assist_human_batch' | 'ai_full_evidence' | 'ai_full_graph' | 'continuous_learning' | 'human_evidence_ai_graph' | 'manual';
  input_payload: Record<string, unknown>;
  plan_payload: Record<string, unknown>;
  generated_resources_payload: Record<string, unknown>;
  decision_payload: Record<string, unknown>;
  policy_payload: Record<string, unknown>;
  explanation_payload: Record<string, unknown>;
  source_ref: string | null;
  workflow_hash: string;
  created_by: string;
  updated_by: string;
  created_at: string;
  updated_at: string;
}

export interface HypothesisListResponse {
  hypotheses: HypothesisResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface HypothesisResponse {
  claim_id: string;
  polarity: string;
  claim_status: string;
  validation_state: string;
  persistability: string;
  confidence: number;
  source_label: string | null;
  relation_type: string;
  target_label: string | null;
  claim_text: string | null;
  linked_relation_id: string | null;
  origin: string;
  seed_entity_ids: string[];
  supporting_provenance_ids: string[];
  reasoning_path_id: string | null;
  supporting_claim_ids: string[];
  direct_supporting_claim_ids: string[];
  transferred_supporting_claim_ids: string[];
  transferred_from_entities: string[];
  transfer_basis: string[];
  contradiction_claim_ids: string[];
  explanation: string | null;
  path_confidence: number | null;
  path_length: number | null;
  created_at: string;
  metadata: Record<string, unknown>;
}

export interface KernelClaimEvidenceListResponse {
  claim_id: string;
  evidence: KernelClaimEvidenceResponse[];
  total: number;
}

export interface KernelClaimEvidenceResponse {
  id: string;
  claim_id: string;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  agent_run_id?: string | null;
  sentence: string | null;
  sentence_source: string | null;
  sentence_confidence: string | null;
  sentence_rationale: string | null;
  figure_reference: string | null;
  table_reference: string | null;
  confidence: number;
  metadata: Record<string, unknown>;
  paper_links?: KernelRelationPaperLinkResponse[];
  created_at: string;
}

export interface KernelClaimMechanismChainResponse {
  root_claim: KernelRelationClaimResponse;
  max_depth: number;
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelEntityBatchCreateRequest {
  entities: KernelEntityCreateRequest[];
}

export interface KernelEntityBatchCreateResponse {
  results: KernelEntityUpsertResponse[];
  created_count: number;
  resolved_count: number;
}

export interface KernelEntityCreateRequest {
  entity_type: string;
  display_label?: string | null;
  aliases?: string[];
  metadata?: Record<string, unknown>;
  identifiers?: Record<string, string>;
}

export interface KernelEntityEmbeddingRefreshRequest {
  entity_ids?: string[] | null;
  limit?: number;
  model_name?: string | null;
  embedding_version?: number | null;
}

export interface KernelEntityEmbeddingRefreshResponse {
  requested: number;
  processed: number;
  refreshed: number;
  unchanged: number;
  failed: number;
  missing_entities: string[];
}

export interface KernelEntityEmbeddingStatusListResponse {
  statuses: KernelEntityEmbeddingStatusResponse[];
  total: number;
}

export interface KernelEntityEmbeddingStatusResponse {
  entity_id: string;
  state: string;
  desired_fingerprint: string;
  embedding_model: string;
  embedding_version: number;
  last_requested_at: string;
  last_attempted_at?: string | null;
  last_refreshed_at?: string | null;
  last_error_code?: string | null;
  last_error_message?: string | null;
}

export interface KernelEntityListResponse {
  entities: KernelEntityResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelEntityResponse {
  id: string;
  research_space_id: string;
  entity_type: string;
  display_label: string | null;
  aliases?: string[];
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelEntitySimilarityListResponse {
  source_entity_id: string;
  results: KernelEntitySimilarityResponse[];
  total: number;
  limit: number;
  min_similarity: number;
}

export interface KernelEntitySimilarityResponse {
  entity_id: string;
  entity_type: string;
  display_label?: string | null;
  similarity_score: number;
  score_breakdown: KernelEntitySimilarityScoreBreakdownResponse;
}

export interface KernelEntitySimilarityScoreBreakdownResponse {
  vector_score: number;
  graph_overlap_score: number;
}

export interface KernelEntityUpdateRequest {
  display_label?: string | null;
  aliases?: string[] | null;
  metadata?: Record<string, unknown> | null;
  identifiers?: Record<string, string> | null;
}

export interface KernelEntityUpsertResponse {
  entity: KernelEntityResponse;
  created: boolean;
}

export interface KernelGraphDocumentCounts {
  entity_nodes: number;
  claim_nodes: number;
  evidence_nodes: number;
  canonical_edges: number;
  claim_participant_edges: number;
  claim_evidence_edges: number;
}

export interface KernelGraphDocumentEdge {
  id: string;
  resource_id?: string | null;
  kind: 'CANONICAL_RELATION' | 'CLAIM_EVIDENCE' | 'CLAIM_PARTICIPANT';
  source_id: string;
  target_id: string;
  type_label: string;
  label: string;
  confidence?: number | null;
  curation_status?: string | null;
  claim_id?: string | null;
  canonical_relation_id?: string | null;
  evidence_id?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelGraphDocumentMeta {
  mode: 'seeded' | 'starter';
  seed_entity_ids: string[];
  requested_depth: number;
  requested_top_k: number;
  pre_cap_entity_node_count: number;
  pre_cap_canonical_edge_count: number;
  truncated_entity_nodes: boolean;
  truncated_canonical_edges: boolean;
  included_claims: boolean;
  included_evidence: boolean;
  max_claims: number;
  evidence_limit_per_claim: number;
  counts: KernelGraphDocumentCounts;
}

export interface KernelGraphDocumentNode {
  id: string;
  resource_id: string;
  kind: 'CLAIM' | 'ENTITY' | 'EVIDENCE';
  type_label: string;
  label: string;
  confidence?: number | null;
  curation_status?: string | null;
  claim_status?: string | null;
  polarity?: string | null;
  canonical_relation_id?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelGraphDocumentRequest {
  mode: 'seeded' | 'starter';
  seed_entity_ids?: string[];
  depth?: number;
  top_k?: number;
  relation_types?: string[] | null;
  curation_statuses?: string[] | null;
  max_nodes?: number;
  max_edges?: number;
  include_claims?: boolean;
  include_evidence?: boolean;
  max_claims?: number;
  evidence_limit_per_claim?: number;
}

export interface KernelGraphDocumentResponse {
  nodes: KernelGraphDocumentNode[];
  edges: KernelGraphDocumentEdge[];
  meta: KernelGraphDocumentMeta;
}

export interface KernelGraphDomainViewResponse {
  view_type: string;
  resource_id: string;
  entity: KernelEntityResponse | null;
  claim: KernelRelationClaimResponse | null;
  paper: KernelSourceDocumentResponse | null;
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelGraphExportResponse {
  nodes: KernelEntityResponse[];
  edges: KernelRelationResponse[];
}

export interface KernelGraphSubgraphMeta {
  mode: 'seeded' | 'starter';
  seed_entity_ids: string[];
  requested_depth: number;
  requested_top_k: number;
  pre_cap_node_count: number;
  pre_cap_edge_count: number;
  truncated_nodes: boolean;
  truncated_edges: boolean;
}

export interface KernelGraphSubgraphRequest {
  mode: 'seeded' | 'starter';
  seed_entity_ids?: string[];
  depth?: number;
  top_k?: number;
  relation_types?: string[] | null;
  curation_statuses?: string[] | null;
  max_nodes?: number;
  max_edges?: number;
}

export interface KernelGraphSubgraphResponse {
  nodes: KernelEntityResponse[];
  edges: KernelRelationResponse[];
  meta: KernelGraphSubgraphMeta;
}

export interface KernelGraphValidationResponse {
  valid: boolean;
  code: 'allowed' | 'conflicting_claim' | 'cross_space_provenance' | 'duplicate_claim' | 'duplicate_entity_candidate' | 'inactive_entity_type' | 'insufficient_evidence' | 'invalid_relation_type' | 'invalid_value_for_variable' | 'missing_ai_provenance' | 'missing_provenance' | 'missing_required_identifier' | 'permission_denied' | 'relation_constraint_not_allowed' | 'relation_constraint_review_only' | 'unknown_entity' | 'unknown_entity_type' | 'unknown_provenance' | 'unknown_relation_type' | 'unknown_subject' | 'unknown_variable';
  message: string;
  severity: 'blocking' | 'info' | 'warning';
  next_actions?: GraphValidationNextAction[];
  claim_ids?: string[];
  normalized_relation_type?: string | null;
  source_type?: string | null;
  target_type?: string | null;
  requires_evidence?: boolean | null;
  profile?: string | null;
  validation_state?: string | null;
  validation_reason?: string | null;
  persistability?: string | null;
}

export interface KernelGraphViewCountsResponse {
  canonical_relations: number;
  claims: number;
  claim_relations: number;
  participants: number;
  evidence: number;
}

export interface KernelMechanisticGapListResponse {
  relation_types: string[];
  intermediate_entity_types: string[];
  source_entity_type?: string | null;
  target_entity_type?: string | null;
  max_hops?: number;
  gaps: KernelMechanisticGapResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelMechanisticGapResponse {
  relation_id: string;
  source_entity_id: string;
  target_entity_id: string;
  relation_type: string;
  source_intermediate_count?: number;
  target_intermediate_count?: number;
  bridge_entity_id?: string | null;
  bridge_path?: string[] | null;
}

export interface KernelObservationCreateRequest {
  subject_id: string;
  variable_id: string;
  value: unknown;
  unit?: string | null;
  observed_at?: string | null;
  provenance_id?: string | null;
  observation_origin?: 'AI_AUTHORED' | 'IMPORTED' | 'MANUAL';
  confidence?: number;
}

export interface KernelObservationListResponse {
  observations: KernelObservationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelObservationResponse {
  id: string;
  research_space_id: string;
  subject_id: string;
  variable_id: string;
  value_numeric: number | null;
  value_text: string | null;
  value_date: string | null;
  value_coded: string | null;
  value_boolean: boolean | null;
  value_json: unknown | null;
  unit: string | null;
  observed_at: string | null;
  provenance_id: string | null;
  confidence: number;
  created_at: string;
  updated_at: string;
}

export interface KernelProvenanceListResponse {
  provenance: KernelProvenanceResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelProvenanceResponse {
  id: string;
  research_space_id: string;
  source_type: string;
  source_ref: string | null;
  extraction_run_id: string | null;
  mapping_method: string | null;
  mapping_confidence: number | null;
  agent_model: string | null;
  raw_input: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

export interface KernelReachabilityGapListResponse {
  seed_entity_id: string;
  max_path_length: number;
  gaps: KernelReachabilityGapResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelReachabilityGapResponse {
  seed_entity_id: string;
  target_entity_id: string;
  min_path_length: number;
  bridge_entity_id?: string | null;
}

export interface KernelReasoningPathDetailResponse {
  path: KernelReasoningPathResponse;
  steps: KernelReasoningPathStepResponse[];
  canonical_relations: KernelRelationResponse[];
  claims: KernelRelationClaimResponse[];
  claim_relations: ClaimRelationResponse[];
  participants: ClaimParticipantResponse[];
  evidence: KernelClaimEvidenceResponse[];
  counts: KernelGraphViewCountsResponse;
}

export interface KernelReasoningPathListResponse {
  paths: KernelReasoningPathResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelReasoningPathResponse {
  id: string;
  research_space_id: string;
  path_kind: string;
  status: string;
  start_entity_id: string;
  end_entity_id: string;
  root_claim_id: string;
  path_length: number;
  confidence: number;
  path_signature_hash: string;
  generated_by: string | null;
  generated_at: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface KernelReasoningPathStepResponse {
  id: string;
  path_id: string;
  step_index: number;
  source_claim_id: string;
  target_claim_id: string;
  claim_relation_id: string;
  canonical_relation_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface KernelRelationClaimCreateRequest {
  source_entity_id: string;
  target_entity_id: string;
  relation_type: string;
  assessment: FactAssessment;
  claim_text?: string | null;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  evidence_sentence_source?: string | null;
  evidence_sentence_confidence?: string | null;
  evidence_sentence_rationale?: string | null;
  source_document_ref?: string | null;
  source_ref?: string | null;
  agent_run_id?: string | null;
  ai_provenance?: ClaimAIProvenanceEnvelope | null;
  metadata?: Record<string, unknown>;
}

export interface KernelRelationClaimListResponse {
  claims: KernelRelationClaimResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationClaimResponse {
  id: string;
  research_space_id: string;
  source_document_id?: string | null;
  source_document_ref?: string | null;
  source_ref?: string | null;
  agent_run_id?: string | null;
  source_type: string;
  relation_type: string;
  target_type: string;
  source_label: string | null;
  target_label: string | null;
  confidence: number;
  validation_state: string;
  validation_reason: string | null;
  persistability: string;
  assertion_class?: string;
  claim_status: string;
  polarity: string;
  claim_text: string | null;
  claim_section: string | null;
  linked_relation_id: string | null;
  metadata: Record<string, unknown>;
  triaged_by: string | null;
  triaged_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface KernelRelationClaimTriageRequest {
  claim_status: string;
}

export interface KernelRelationConflictListResponse {
  conflicts: KernelRelationConflictResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationConflictResponse {
  relation_id: string;
  support_count: number;
  refute_count: number;
  support_claim_ids: string[];
  refute_claim_ids: string[];
  support_confidence?: number;
  refute_confidence?: number;
  relation_type?: string | null;
}

export interface KernelRelationCreateRequest {
  source_id: string;
  relation_type: string;
  target_id: string;
  assessment: FactAssessment;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  evidence_sentence_source?: string | null;
  evidence_sentence_confidence?: string | null;
  evidence_sentence_rationale?: string | null;
  evidence_tier?: string | null;
  provenance_id?: string | null;
  source_document_ref?: string | null;
  metadata?: Record<string, unknown>;
}

export interface KernelRelationCurationUpdateRequest {
  curation_status: string;
}

export interface KernelRelationListResponse {
  relations: KernelRelationResponse[];
  total: number;
  offset: number;
  limit: number;
}

export interface KernelRelationPaperLinkResponse {
  label: string;
  url: string;
  source: string;
}

export interface KernelRelationResponse {
  id: string;
  research_space_id: string;
  source_claim_id?: string | null;
  source_id: string;
  relation_type: string;
  target_id: string;
  confidence: number;
  aggregate_confidence: number;
  source_count: number;
  highest_evidence_tier: string | null;
  support_confidence?: number;
  refute_confidence?: number;
  distinct_source_family_count?: number;
  curation_status: string;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  evidence_sentence_source?: string | null;
  evidence_sentence_confidence?: string | null;
  evidence_sentence_rationale?: string | null;
  paper_links?: KernelRelationPaperLinkResponse[];
  provenance_id: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface KernelRelationSuggestionConstraintCheckResponse {
  passed: boolean;
  source_entity_type: string;
  relation_type: string;
  target_entity_type: string;
}

export interface KernelRelationSuggestionListResponse {
  suggestions: KernelRelationSuggestionResponse[];
  total: number;
  limit_per_source: number;
  min_score: number;
  incomplete?: boolean;
  skipped_sources?: KernelRelationSuggestionSkippedSourceResponse[];
}

export interface KernelRelationSuggestionRequest {
  source_entity_ids: string[];
  limit_per_source?: number;
  min_score?: number;
  allowed_relation_types?: string[] | null;
  target_entity_types?: string[] | null;
  exclude_existing_relations?: boolean;
  require_all_ready?: boolean;
}

export interface KernelRelationSuggestionResponse {
  source_entity_id: string;
  target_entity_id: string;
  relation_type: string;
  final_score: number;
  score_breakdown: KernelRelationSuggestionScoreBreakdownResponse;
  constraint_check: KernelRelationSuggestionConstraintCheckResponse;
}

export interface KernelRelationSuggestionScoreBreakdownResponse {
  vector_score: number;
  graph_overlap_score: number;
  relation_prior_score: number;
}

export interface KernelRelationSuggestionSkippedSourceResponse {
  entity_id: string;
  state: string;
  reason: string;
}

export interface KernelRelationTripleValidationRequest {
  source_entity_id: string;
  target_entity_id: string;
  relation_type: string;
  evidence_summary?: string | null;
  evidence_sentence?: string | null;
  source_document_ref?: string | null;
}

export interface KernelSourceDocumentResponse {
  id: string;
  research_space_id: string | null;
  source_id: string;
  external_record_id: string;
  source_type: string;
  document_format: string;
  enrichment_status: string;
  extraction_status: string;
  metadata: Record<string, unknown>;
  created_at: string | null;
  updated_at: string | null;
}

export interface OperatingModeCapabilitiesResponse {
  research_space_id: string;
  mode: 'ai_assist_human_batch' | 'ai_full_evidence' | 'ai_full_graph' | 'continuous_learning' | 'human_evidence_ai_graph' | 'manual';
  capabilities: Record<string, unknown>;
}

export interface OperatingModeRequest {
  mode: 'ai_assist_human_batch' | 'ai_full_evidence' | 'ai_full_graph' | 'continuous_learning' | 'human_evidence_ai_graph' | 'manual';
  workflow_policy?: GraphWorkflowPolicy;
}

export interface OperatingModeResponse {
  research_space_id: string;
  mode: 'ai_assist_human_batch' | 'ai_full_evidence' | 'ai_full_graph' | 'continuous_learning' | 'human_evidence_ai_graph' | 'manual';
  workflow_policy: GraphWorkflowPolicy;
  capabilities: Record<string, unknown>;
}

export interface RelationConstraintListResponse {
  constraints: RelationConstraintResponse[];
  total: number;
}

export interface RelationConstraintResponse {
  id: number;
  source_type: string;
  relation_type: string;
  target_type: string;
  is_allowed: boolean;
  requires_evidence: boolean;
  profile: string;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface TransformRegistryListResponse {
  transforms: TransformRegistryResponse[];
  total: number;
}

export interface TransformRegistryResponse {
  id: string;
  input_unit: string;
  output_unit: string;
  category: string;
  input_data_type: string | null;
  output_data_type: string | null;
  implementation_ref: string;
  is_deterministic: boolean;
  is_production_allowed: boolean;
  test_input: unknown | null;
  expected_output: unknown | null;
  description: string | null;
  status: string;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface TransformVerificationResponse {
  transform_id: string;
  passed: boolean;
  message: string;
  actual_output: unknown | null;
  expected_output: unknown | null;
  checked_at: string;
}

export interface ValidationExplanationRequest {
  validation_payload?: Record<string, unknown>;
  context_payload?: Record<string, unknown>;
}

export interface ValueSetCreateRequest {
  id: string;
  variable_id: string;
  name: string;
  description?: string | null;
  external_ref?: string | null;
  is_extensible?: boolean;
  source_ref?: string | null;
}

export interface ValueSetItemActiveRequest {
  is_active: boolean;
  revocation_reason?: string | null;
}

export interface ValueSetItemCreateRequest {
  code: string;
  display_label: string;
  synonyms?: string[];
  external_ref?: string | null;
  sort_order?: number;
  is_active?: boolean;
  source_ref?: string | null;
}

export interface ValueSetItemListResponse {
  items: ValueSetItemResponse[];
  total: number;
}

export interface ValueSetItemResponse {
  id: number;
  value_set_id: string;
  code: string;
  display_label: string;
  synonyms: string[];
  external_ref: string | null;
  sort_order: number;
  is_active: boolean;
  created_by: string;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ValueSetListResponse {
  value_sets: ValueSetResponse[];
  total: number;
}

export interface ValueSetResponse {
  id: string;
  variable_id: string;
  variable_data_type: string;
  name: string;
  description: string | null;
  external_ref: string | null;
  is_extensible: boolean;
  created_by: string;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface VariableDefinitionCreateRequest {
  id: string;
  canonical_name: string;
  display_name: string;
  data_type: 'INTEGER' | 'FLOAT' | 'STRING' | 'DATE' | 'CODED' | 'BOOLEAN' | 'JSON';
  domain_context?: string;
  sensitivity?: 'PUBLIC' | 'INTERNAL' | 'PHI';
  preferred_unit?: string | null;
  constraints?: Record<string, unknown>;
  description?: string | null;
  source_ref?: string | null;
}

export interface VariableDefinitionListResponse {
  variables: VariableDefinitionResponse[];
  total: number;
}

export interface VariableDefinitionResponse {
  id: string;
  canonical_name: string;
  display_name: string;
  data_type: 'INTEGER' | 'FLOAT' | 'STRING' | 'DATE' | 'CODED' | 'BOOLEAN' | 'JSON';
  preferred_unit: string | null;
  constraints: Record<string, unknown>;
  domain_context: string;
  sensitivity: 'PUBLIC' | 'INTERNAL' | 'PHI';
  description: string | null;
  description_embedding: number[] | null;
  embedded_at: string | null;
  embedding_model: string | null;
  created_by: string;
  is_active: boolean;
  valid_from: string | null;
  valid_to: string | null;
  superseded_by: string | null;
  source_ref: string | null;
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  reviewed_by: string | null;
  reviewed_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface VariableDefinitionReviewStatusRequest {
  review_status: 'ACTIVE' | 'PENDING_REVIEW' | 'REVOKED';
  revocation_reason?: string | null;
}

export interface VariableDefinitionRevokeRequest {
  reason: string;
}
