"""Builtin graph relation synonym seed data."""

from __future__ import annotations

from artana_evidence_db.graph_domain_types import BuiltinRelationSynonymDefinition


def _syn(relation_type: str, synonym: str) -> BuiltinRelationSynonymDefinition:
    return BuiltinRelationSynonymDefinition(
        relation_type=relation_type,
        synonym=synonym,
        source="graph_service",
    )


GRAPH_SERVICE_BUILTIN_RELATION_SYNONYMS = (
    # --- ASSOCIATED_WITH (generic association) ---
    _syn("ASSOCIATED_WITH", "ASSOCIATES_WITH"),
    _syn("ASSOCIATED_WITH", "LINKED_TO"),
    _syn("ASSOCIATED_WITH", "CORRELATED_WITH"),
    _syn("ASSOCIATED_WITH", "RELATED_TO"),
    _syn("ASSOCIATED_WITH", "CONNECTED_TO"),
    _syn("ASSOCIATED_WITH", "IMPLICATED_IN"),
    _syn("ASSOCIATED_WITH", "TIED_TO"),
    _syn("ASSOCIATED_WITH", "OBSERVED_IN"),
    _syn("ASSOCIATED_WITH", "REPORTED_IN"),
    _syn("ASSOCIATED_WITH", "FOUND_IN_CASES_OF"),
    # --- CAUSES (causal) ---
    _syn("CAUSES", "LEADS_TO"),
    _syn("CAUSES", "RESULTS_IN"),
    _syn("CAUSES", "INDUCES"),
    _syn("CAUSES", "PRODUCES"),
    _syn("CAUSES", "GIVES_RISE_TO"),
    _syn("CAUSES", "TRIGGERS"),
    _syn("CAUSES", "ELICITS"),
    _syn("CAUSES", "DRIVES"),
    _syn("CAUSES", "ENGENDERS"),
    # --- TREATS (therapeutic) ---
    _syn("TREATS", "THERAPEUTIC_FOR"),
    _syn("TREATS", "AMELIORATES"),
    _syn("TREATS", "ALLEVIATES"),
    _syn("TREATS", "USED_TO_TREAT"),
    _syn("TREATS", "REVERSES"),
    _syn("TREATS", "CURES"),
    _syn("TREATS", "MANAGES"),
    _syn("TREATS", "MITIGATES"),
    _syn("TREATS", "RESOLVES"),
    # --- TARGETS (drug/molecular target) ---
    _syn("TARGETS", "ACTS_ON"),
    _syn("TARGETS", "BINDS_TO"),
    _syn("TARGETS", "DIRECTED_AT"),
    _syn("TARGETS", "ENGAGES"),
    _syn("TARGETS", "ATTACKS"),
    _syn("TARGETS", "ACTS_AGAINST"),
    # --- BIOMARKER_FOR ---
    _syn("BIOMARKER_FOR", "DIAGNOSTIC_FOR"),
    _syn("BIOMARKER_FOR", "PROGNOSTIC_FOR"),
    _syn("BIOMARKER_FOR", "INDICATIVE_OF"),
    _syn("BIOMARKER_FOR", "MARKER_FOR"),
    _syn("BIOMARKER_FOR", "PREDICTOR_OF"),
    _syn("BIOMARKER_FOR", "INDICATOR_OF"),
    _syn("BIOMARKER_FOR", "READ_OUT_FOR"),
    # --- PHYSICALLY_INTERACTS_WITH ---
    _syn("PHYSICALLY_INTERACTS_WITH", "INTERACTS_WITH"),
    _syn("PHYSICALLY_INTERACTS_WITH", "BINDS"),
    _syn("PHYSICALLY_INTERACTS_WITH", "COMPLEXES_WITH"),
    _syn("PHYSICALLY_INTERACTS_WITH", "DIMERIZES_WITH"),
    _syn("PHYSICALLY_INTERACTS_WITH", "FORMS_COMPLEX_WITH"),
    _syn("PHYSICALLY_INTERACTS_WITH", "INTERACTS_PHYSICALLY_WITH"),
    _syn("PHYSICALLY_INTERACTS_WITH", "DOCKS_WITH"),
    # --- ACTIVATES (regulation) ---
    _syn("ACTIVATES", "STIMULATES"),
    _syn("ACTIVATES", "ENHANCES"),
    _syn("ACTIVATES", "PROMOTES"),
    _syn("ACTIVATES", "UPREGULATES"),
    _syn("ACTIVATES", "INDUCES_EXPRESSION_OF"),
    _syn("ACTIVATES", "TURNS_ON"),
    _syn("ACTIVATES", "INITIATES"),
    _syn("ACTIVATES", "SWITCHES_ON"),
    _syn("ACTIVATES", "AUGMENTS"),
    # --- INHIBITS (regulation) ---
    _syn("INHIBITS", "SUPPRESSES"),
    _syn("INHIBITS", "REPRESSES"),
    _syn("INHIBITS", "BLOCKS"),
    _syn("INHIBITS", "DOWNREGULATES"),
    _syn("INHIBITS", "ATTENUATES"),
    _syn("INHIBITS", "SILENCES"),
    _syn("INHIBITS", "DAMPENS"),
    _syn("INHIBITS", "ANTAGONIZES"),
    _syn("INHIBITS", "ABROGATES"),
    _syn("INHIBITS", "ABOLISHES"),
    # --- REGULATES (regulation) ---
    _syn("REGULATES", "CONTROLS"),
    _syn("REGULATES", "GOVERNS"),
    _syn("REGULATES", "INFLUENCES"),
    _syn("REGULATES", "ORCHESTRATES"),
    _syn("REGULATES", "COORDINATES"),
    _syn("REGULATES", "MEDIATES"),
    # --- UPSTREAM_OF / DOWNSTREAM_OF (pathway ordering) ---
    _syn("UPSTREAM_OF", "PRECEDES"),
    _syn("UPSTREAM_OF", "SIGNALS_TO"),
    _syn("UPSTREAM_OF", "FEEDS_INTO"),
    _syn("UPSTREAM_OF", "ACTS_BEFORE"),
    _syn("UPSTREAM_OF", "PRECEDES_IN_PATHWAY"),
    _syn("DOWNSTREAM_OF", "FOLLOWS"),
    _syn("DOWNSTREAM_OF", "RECEIVES_SIGNAL_FROM"),
    _syn("DOWNSTREAM_OF", "TRIGGERED_BY"),
    _syn("DOWNSTREAM_OF", "ACTS_AFTER"),
    _syn("DOWNSTREAM_OF", "FOLLOWS_IN_PATHWAY"),
    # --- PART_OF (compositional) ---
    _syn("PART_OF", "SUBUNIT_OF"),
    _syn("PART_OF", "CONTAINED_IN"),
    _syn("PART_OF", "MEMBER_OF"),
    _syn("PART_OF", "BELONGS_TO"),
    _syn("PART_OF", "INCLUDED_IN"),
    _syn("PART_OF", "INTEGRAL_PART_OF"),
    # --- COMPONENT_OF (compositional) ---
    _syn("COMPONENT_OF", "CONSTITUENT_OF"),
    _syn("COMPONENT_OF", "ELEMENT_OF"),
    _syn("COMPONENT_OF", "SUBSTRUCTURE_OF"),
    _syn("COMPONENT_OF", "BUILDING_BLOCK_OF"),
    # --- EXPRESSED_IN (spatial biology) ---
    _syn("EXPRESSED_IN", "EXPRESSED_WITHIN"),
    _syn("EXPRESSED_IN", "EXPRESSED_BY"),
    _syn("EXPRESSED_IN", "SHOWS_EXPRESSION_IN"),
    _syn("EXPRESSED_IN", "DETECTED_IN"),
    _syn("EXPRESSED_IN", "PRESENT_IN"),
    _syn("EXPRESSED_IN", "TRANSCRIBED_IN"),
    _syn("EXPRESSED_IN", "ENRICHED_IN"),
    _syn("EXPRESSED_IN", "ABUNDANT_IN"),
    # --- PARTICIPATES_IN (process participation) ---
    _syn("PARTICIPATES_IN", "INVOLVED_IN"),
    _syn("PARTICIPATES_IN", "FUNCTIONS_IN"),
    _syn("PARTICIPATES_IN", "TAKES_PART_IN"),
    _syn("PARTICIPATES_IN", "CONTRIBUTES_TO"),
    _syn("PARTICIPATES_IN", "PLAYS_ROLE_IN"),
    _syn("PARTICIPATES_IN", "ACTIVE_IN"),
    _syn("PARTICIPATES_IN", "OPERATES_IN"),
    # --- LOCATED_IN (localization) ---
    _syn("LOCATED_IN", "LOCALIZES_TO"),
    _syn("LOCATED_IN", "FOUND_IN"),
    _syn("LOCATED_IN", "RESIDES_IN"),
    _syn("LOCATED_IN", "LOCALIZED_TO"),
    _syn("LOCATED_IN", "PRESENT_AT"),
    _syn("LOCATED_IN", "SITUATED_IN"),
    _syn("LOCATED_IN", "CONFINED_TO"),
    # --- SUPPORTS (evidence/governance) ---
    _syn("SUPPORTS", "PROVIDES_EVIDENCE_FOR"),
    _syn("SUPPORTS", "BACKS"),
    _syn("SUPPORTS", "CORROBORATES"),
    _syn("SUPPORTS", "VALIDATES"),
    _syn("SUPPORTS", "CONFIRMS"),
    _syn("SUPPORTS", "REINFORCES"),
    # --- REFINES (evidence/governance) ---
    _syn("REFINES", "NARROWS"),
    _syn("REFINES", "SPECIALIZES"),
    _syn("REFINES", "MAKES_MORE_SPECIFIC"),
    # --- GENERALIZES (evidence/governance) ---
    _syn("GENERALIZES", "BROADENS"),
    _syn("GENERALIZES", "ABSTRACTS"),
    _syn("GENERALIZES", "MAKES_MORE_GENERAL"),
    # --- INSTANCE_OF (evidence/governance) ---
    _syn("INSTANCE_OF", "EXAMPLE_OF"),
    _syn("INSTANCE_OF", "IS_A"),
    _syn("INSTANCE_OF", "TYPE_OF"),
    _syn("INSTANCE_OF", "KIND_OF"),
    # --- MENTIONS (document governance) ---
    _syn("MENTIONS", "REFERENCES"),
    _syn("MENTIONS", "DISCUSSES"),
    _syn("MENTIONS", "DESCRIBES"),
    _syn("MENTIONS", "NOTES"),
    _syn("MENTIONS", "REPORTS"),
    _syn("MENTIONS", "COVERS"),
    # --- CITES (document governance) ---
    _syn("CITES", "REFERENCES_PUBLICATION"),
    _syn("CITES", "CITED_BY"),
    _syn("CITES", "REFERS_TO"),
    _syn("CITES", "ACKNOWLEDGES"),
    # --- HAS_AUTHOR (document governance) ---
    _syn("HAS_AUTHOR", "AUTHORED_BY"),
    _syn("HAS_AUTHOR", "WRITTEN_BY"),
    _syn("HAS_AUTHOR", "PUBLISHED_BY"),
    # --- HAS_KEYWORD (document governance) ---
    _syn("HAS_KEYWORD", "TAGGED_WITH"),
    _syn("HAS_KEYWORD", "INDEXED_AS"),
    _syn("HAS_KEYWORD", "LABELED_WITH"),
    # --- MODULATES ---
    _syn("MODULATES", "MODULATES_ACTIVITY_OF"),
    _syn("MODULATES", "AFFECTS"),
    _syn("MODULATES", "ALTERS"),
    _syn("MODULATES", "TUNES"),
    _syn("MODULATES", "ADJUSTS"),
    # --- LOSS_OF_FUNCTION / GAIN_OF_FUNCTION ---
    _syn("LOSS_OF_FUNCTION", "LOF"),
    _syn("LOSS_OF_FUNCTION", "LOSS_OF_FUNCTION_IN"),
    _syn("LOSS_OF_FUNCTION", "ABLATES_FUNCTION_OF"),
    _syn("LOSS_OF_FUNCTION", "KNOCKS_OUT"),
    _syn("LOSS_OF_FUNCTION", "NULL_FOR"),
    _syn("LOSS_OF_FUNCTION", "INACTIVATES"),
    _syn("GAIN_OF_FUNCTION", "GOF"),
    _syn("GAIN_OF_FUNCTION", "GAIN_OF_FUNCTION_IN"),
    _syn("GAIN_OF_FUNCTION", "CONFERS_ACTIVITY_TO"),
    _syn("GAIN_OF_FUNCTION", "HYPERACTIVATES"),
    _syn("GAIN_OF_FUNCTION", "CONSTITUTIVELY_ACTIVATES"),
    # --- PREDISPOSES_TO ---
    _syn("PREDISPOSES_TO", "RISK_FACTOR_FOR"),
    _syn("PREDISPOSES_TO", "INCREASES_RISK_OF"),
    _syn("PREDISPOSES_TO", "SUSCEPTIBILITY_TO"),
    _syn("PREDISPOSES_TO", "CONFERS_SUSCEPTIBILITY"),
    _syn("PREDISPOSES_TO", "ELEVATES_RISK_OF"),
    _syn("PREDISPOSES_TO", "PREDISPOSES"),
    # --- CO_OCCURS_WITH ---
    _syn("CO_OCCURS_WITH", "COINCIDES_WITH"),
    _syn("CO_OCCURS_WITH", "COMORBID_WITH"),
    _syn("CO_OCCURS_WITH", "CO_PRESENTS_WITH"),
    _syn("CO_OCCURS_WITH", "COEXISTS_WITH"),
    _syn("CO_OCCURS_WITH", "FOUND_TOGETHER_WITH"),
    # --- SENSITIZES_TO ---
    _syn("SENSITIZES_TO", "INCREASES_SENSITIVITY_TO"),
    _syn("SENSITIZES_TO", "CONFERS_SENSITIVITY_TO"),
    _syn("SENSITIZES_TO", "RENDERS_SENSITIVE_TO"),
    _syn("SENSITIZES_TO", "ENHANCES_SENSITIVITY_TO"),
    _syn("SENSITIZES_TO", "MAKES_VULNERABLE_TO"),
    # --- PHENOCOPY_OF ---
    _syn("PHENOCOPY_OF", "PHENOTYPICALLY_MIMICS"),
    _syn("PHENOCOPY_OF", "CLINICALLY_INDISTINGUISHABLE_FROM"),
    _syn("PHENOCOPY_OF", "MIMICS"),
    _syn("PHENOCOPY_OF", "PHENOTYPICALLY_RESEMBLES"),
    _syn("PHENOCOPY_OF", "MIMICS_PHENOTYPE_OF"),
    # --- COLOCALIZES_WITH ---
    _syn("COLOCALIZES_WITH", "CO_LOCALIZES_WITH"),
    _syn("COLOCALIZES_WITH", "FOUND_WITH"),
    _syn("COLOCALIZES_WITH", "CO_EXPRESSED_WITH"),
    _syn("COLOCALIZES_WITH", "OCCUPIES_SAME_REGION_AS"),
    _syn("COLOCALIZES_WITH", "COMPARTMENTALIZED_WITH"),
    # --- COMPENSATED_BY ---
    _syn("COMPENSATED_BY", "RESCUED_BY"),
    _syn("COMPENSATED_BY", "FUNCTIONALLY_REPLACED_BY"),
    _syn("COMPENSATED_BY", "REDUNDANT_WITH"),
    _syn("COMPENSATED_BY", "SUBSTITUTED_BY"),
    _syn("COMPENSATED_BY", "BACKED_UP_BY"),
    # --- SUBSTRATE_OF ---
    _syn("SUBSTRATE_OF", "CLEAVED_BY"),
    _syn("SUBSTRATE_OF", "PHOSPHORYLATED_BY"),
    _syn("SUBSTRATE_OF", "ACTED_UPON_BY"),
    _syn("SUBSTRATE_OF", "HYDROLYZED_BY"),
    _syn("SUBSTRATE_OF", "MODIFIED_BY"),
    _syn("SUBSTRATE_OF", "PROCESSED_BY"),
    # --- TRANSPORTS ---
    _syn("TRANSPORTS", "CARRIES"),
    _syn("TRANSPORTS", "SHUTTLES"),
    _syn("TRANSPORTS", "TRANSLOCATES"),
    _syn("TRANSPORTS", "MOVES"),
    _syn("TRANSPORTS", "FERRIES"),
    _syn("TRANSPORTS", "EXPORTS"),
    _syn("TRANSPORTS", "IMPORTS"),
)


