"""Builtin graph relation constraint seed data."""

from __future__ import annotations

from artana_evidence_db.graph_domain_types import BuiltinRelationConstraintDefinition

GRAPH_SERVICE_BUILTIN_RELATION_CONSTRAINTS = (
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="ASSOCIATED_WITH",
        target_type="PHENOTYPE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="ASSOCIATED_WITH",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="PHYSICALLY_INTERACTS_WITH",
        target_type="GENE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="PARTICIPATES_IN",
        target_type="SIGNALING_PATHWAY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="PHYSICALLY_INTERACTS_WITH",
        target_type="PROTEIN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="ASSOCIATED_WITH",
        target_type="PHENOTYPE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="ASSOCIATED_WITH",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="CAUSES",
        target_type="PHENOTYPE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="CAUSES",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="TARGETS",
        target_type="GENE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="TARGETS",
        target_type="PROTEIN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="TARGETS",
        target_type="SIGNALING_PATHWAY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="TREATS",
        target_type="PHENOTYPE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="TREATS",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="MENTIONS",
        target_type="GENE",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="MENTIONS",
        target_type="PROTEIN",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="MENTIONS",
        target_type="VARIANT",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="MENTIONS",
        target_type="PHENOTYPE",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="MENTIONS",
        target_type="DRUG",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="SUPPORTS",
        target_type="GENE",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="SUPPORTS",
        target_type="PROTEIN",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="SUPPORTS",
        target_type="VARIANT",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="CITES",
        target_type="PUBLICATION",
        requires_evidence=False,
    ),
    # --- TISSUE constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="EXPRESSED_IN",
        target_type="TISSUE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="EXPRESSED_IN",
        target_type="TISSUE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="TISSUE",
        relation_type="PART_OF",
        target_type="TISSUE",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="TISSUE",
        relation_type="ASSOCIATED_WITH",
        target_type="DISEASE",
    ),
    # --- CELL_TYPE constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="EXPRESSED_IN",
        target_type="CELL_TYPE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="EXPRESSED_IN",
        target_type="CELL_TYPE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CELL_TYPE",
        relation_type="PART_OF",
        target_type="TISSUE",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CELL_TYPE",
        relation_type="PARTICIPATES_IN",
        target_type="BIOLOGICAL_PROCESS",
    ),
    # --- CELLULAR_COMPARTMENT constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="LOCATED_IN",
        target_type="CELLULAR_COMPARTMENT",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN_COMPLEX",
        relation_type="LOCATED_IN",
        target_type="CELLULAR_COMPARTMENT",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CELLULAR_COMPARTMENT",
        relation_type="PART_OF",
        target_type="CELLULAR_COMPARTMENT",
        requires_evidence=False,
    ),
    # --- BIOLOGICAL_PROCESS constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="PARTICIPATES_IN",
        target_type="BIOLOGICAL_PROCESS",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="PARTICIPATES_IN",
        target_type="BIOLOGICAL_PROCESS",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="BIOLOGICAL_PROCESS",
        relation_type="PART_OF",
        target_type="BIOLOGICAL_PROCESS",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="BIOLOGICAL_PROCESS",
        relation_type="UPSTREAM_OF",
        target_type="BIOLOGICAL_PROCESS",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="BIOLOGICAL_PROCESS",
        relation_type="ASSOCIATED_WITH",
        target_type="DISEASE",
    ),
    # --- PROTEIN_DOMAIN constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="LOCATED_IN",
        target_type="PROTEIN_DOMAIN",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN_DOMAIN",
        relation_type="PART_OF",
        target_type="PROTEIN",
        requires_evidence=False,
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN_DOMAIN",
        relation_type="PHYSICALLY_INTERACTS_WITH",
        target_type="PROTEIN_DOMAIN",
    ),
    # --- MODEL_ORGANISM constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="MODEL_ORGANISM",
        relation_type="ASSOCIATED_WITH",
        target_type="GENE",
        profile="REVIEW_ONLY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="MODEL_ORGANISM",
        relation_type="ASSOCIATED_WITH",
        target_type="PHENOTYPE",
        profile="REVIEW_ONLY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="MODEL_ORGANISM",
        relation_type="ASSOCIATED_WITH",
        target_type="DISEASE",
        profile="REVIEW_ONLY",
    ),
    # --- CLINICAL_TRIAL constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="TARGETS",
        target_type="DISEASE",
        profile="REVIEW_ONLY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="TARGETS",
        target_type="GENE",
        profile="REVIEW_ONLY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="BIOMARKER_FOR",
        target_type="CLINICAL_TRIAL",
        profile="REVIEW_ONLY",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="ASSOCIATED_WITH",
        target_type="DRUG",
        profile="REVIEW_ONLY",
    ),
    # --- MODULATES constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="MODULATES",
        target_type="GENE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="MODULATES",
        target_type="PROTEIN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="MODULATES",
        target_type="BIOLOGICAL_PROCESS",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="MODULATES",
        target_type="SIGNALING_PATHWAY",
    ),
    # --- LOSS_OF_FUNCTION / GAIN_OF_FUNCTION constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="LOSS_OF_FUNCTION",
        target_type="GENE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="GAIN_OF_FUNCTION",
        target_type="GENE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="LOSS_OF_FUNCTION",
        target_type="PROTEIN",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="GAIN_OF_FUNCTION",
        target_type="PROTEIN",
        profile="EXPECTED",
    ),
    # --- PREDISPOSES_TO constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="PREDISPOSES_TO",
        target_type="DISEASE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="PREDISPOSES_TO",
        target_type="PHENOTYPE",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="PREDISPOSES_TO",
        target_type="DISEASE",
    ),
    # --- CO_OCCURS_WITH constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="CO_OCCURS_WITH",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="CO_OCCURS_WITH",
        target_type="PHENOTYPE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="CO_OCCURS_WITH",
        target_type="PHENOTYPE",
    ),
    # --- SENSITIZES_TO constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="VARIANT",
        relation_type="SENSITIZES_TO",
        target_type="DRUG",
        profile="EXPECTED",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="SENSITIZES_TO",
        target_type="DRUG",
    ),
    # --- PHENOCOPY_OF constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="PHENOCOPY_OF",
        target_type="DISEASE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="SYNDROME",
        relation_type="PHENOCOPY_OF",
        target_type="SYNDROME",
    ),
    # --- COLOCALIZES_WITH constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="COLOCALIZES_WITH",
        target_type="PROTEIN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="COLOCALIZES_WITH",
        target_type="GENE",
    ),
    # --- COMPENSATED_BY constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="GENE",
        relation_type="COMPENSATED_BY",
        target_type="GENE",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="COMPENSATED_BY",
        target_type="PROTEIN",
    ),
    # --- SUBSTRATE_OF constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="SUBSTRATE_OF",
        target_type="PROTEIN",
    ),
    # --- TRANSPORTS constraints ---
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="TRANSPORTS",
        target_type="PROTEIN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PROTEIN",
        relation_type="TRANSPORTS",
        target_type="DRUG",
    ),
    # --- FORBIDDEN constraints (nonsensical combinations) ---
    # Wildcard target_type="*" means the source can never appear with that
    # relation regardless of target.  Exact-match constraints take priority
    # over wildcards in the lookup (see get_triple_profile).
    #
    # PUBLICATION: describes causation, doesn't cause/treat/interact/express
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="CAUSES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="PHYSICALLY_INTERACTS_WITH",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="ACTIVATES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="INHIBITS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="EXPRESSED_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="LOSS_OF_FUNCTION",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PUBLICATION",
        relation_type="GAIN_OF_FUNCTION",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # DRUG: not expressed, no variants, doesn't participate in processes
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="EXPRESSED_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="LOSS_OF_FUNCTION",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="GAIN_OF_FUNCTION",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DRUG",
        relation_type="PARTICIPATES_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # PHENOTYPE: observable trait, doesn't target/activate/inhibit/treat/express
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="TARGETS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="ACTIVATES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="INHIBITS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="PHENOTYPE",
        relation_type="EXPRESSED_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # DISEASE: doesn't target/activate/inhibit/treat/express
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="TARGETS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="ACTIVATES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="INHIBITS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="DISEASE",
        relation_type="EXPRESSED_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # TISSUE: doesn't cause disease, doesn't treat/target
    BuiltinRelationConstraintDefinition(
        source_type="TISSUE",
        relation_type="CAUSES",
        target_type="DISEASE",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="TISSUE",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="TISSUE",
        relation_type="TARGETS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # CLINICAL_TRIAL: not molecular, not expressed, doesn't cause
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="PHYSICALLY_INTERACTS_WITH",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="EXPRESSED_IN",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CLINICAL_TRIAL",
        relation_type="CAUSES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # MODEL_ORGANISM: doesn't treat/target
    BuiltinRelationConstraintDefinition(
        source_type="MODEL_ORGANISM",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="MODEL_ORGANISM",
        relation_type="TARGETS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    # CELLULAR_COMPARTMENT: doesn't cause/treat
    BuiltinRelationConstraintDefinition(
        source_type="CELLULAR_COMPARTMENT",
        relation_type="CAUSES",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
    BuiltinRelationConstraintDefinition(
        source_type="CELLULAR_COMPARTMENT",
        relation_type="TREATS",
        target_type="*",
        requires_evidence=False,
        profile="FORBIDDEN",
    ),
)


