"""TG-04 n-ary claim benchmark contracts and fixture loading."""

from scripts.validation.claim_events.contracts import (
    AnnotationProvenance,
    AnnotationStatus,
    ArtanaParticipantRole,
    BenchmarkEligibility,
    BenchmarkEligibilityStatus,
    BenchmarkEventType,
    BenchmarkMetadata,
    ClaimArgument,
    EpistemicStatus,
    EventRole,
    EventType,
    ExactTrigger,
    FramingDecision,
    NaryClaimCase,
    NaryClaimEvent,
    NaryClaimFixture,
    NaryClaimGold,
    Polarity,
    ProjectionAnnotation,
    ProjectionEligibilityStatus,
    SourceIdentity,
    SourceLocator,
    SourceSpan,
    SupportedProjection,
    ValueAnnotation,
    ValueStatus,
    validate_event_type_parity,
)
from scripts.validation.claim_events.fixture import SCHEMA_VERSION, load_fixture

__all__ = [
    "AnnotationProvenance",
    "AnnotationStatus",
    "ArtanaParticipantRole",
    "BenchmarkEligibility",
    "BenchmarkEligibilityStatus",
    "BenchmarkEventType",
    "BenchmarkMetadata",
    "ClaimArgument",
    "EpistemicStatus",
    "EventRole",
    "EventType",
    "ExactTrigger",
    "FramingDecision",
    "NaryClaimCase",
    "NaryClaimEvent",
    "NaryClaimFixture",
    "NaryClaimGold",
    "Polarity",
    "ProjectionAnnotation",
    "ProjectionEligibilityStatus",
    "SCHEMA_VERSION",
    "SourceIdentity",
    "SourceLocator",
    "SourceSpan",
    "SupportedProjection",
    "ValueAnnotation",
    "ValueStatus",
    "load_fixture",
    "validate_event_type_parity",
]
