"""Public v2 route alias registration."""

from __future__ import annotations

from collections.abc import Sequence

from fastapi import APIRouter
from fastapi.routing import APIRoute

from . import (
    authentication,
    chat,
    continuous_learning_runs,
    documents,
    full_ai_orchestrator_runs,
    graph_connection_runs,
    graph_explorer,
    graph_search_runs,
    hypothesis_runs,
    marrvel,
    mechanism_discovery_runs,
    proposals,
    research_onboarding_runs,
    research_state,
    review_queue,
    schedules,
    spaces,
    supervisor_runs,
)


def _find_route(source_router: APIRouter, *, path: str, method: str) -> APIRoute:
    for route in source_router.routes:
        if (
            isinstance(route, APIRoute)
            and route.path == path
            and method.upper() in route.methods
        ):
            return route
    msg = f"Missing source route for v2 alias: {method.upper()} {path}"
    raise RuntimeError(msg)


def _add_alias(
    *,
    target_router: APIRouter,
    source_router: APIRouter,
    source_path: str,
    target_path: str,
    method: str,
    summary: str,
    tags: Sequence[str],
) -> None:
    source = _find_route(source_router, path=source_path, method=method)
    target_router.add_api_route(
        target_path,
        source.endpoint,
        response_model=source.response_model,
        status_code=source.status_code,
        tags=list(tags),
        dependencies=source.dependencies,
        summary=summary,
        description=source.description,
        response_description=source.response_description,
        responses=source.responses,
        deprecated=source.deprecated,
        methods=[method.upper()],
        response_model_include=source.response_model_include,
        response_model_exclude=source.response_model_exclude,
        response_model_by_alias=source.response_model_by_alias,
        response_model_exclude_unset=source.response_model_exclude_unset,
        response_model_exclude_defaults=source.response_model_exclude_defaults,
        response_model_exclude_none=source.response_model_exclude_none,
        include_in_schema=source.include_in_schema,
        response_class=source.response_class,
        name=f"v2_{source.name}",
        callbacks=source.callbacks,
        openapi_extra=source.openapi_extra,
    )


_ALIASES = (
    # Account and space setup.
    (
        authentication.router,
        "POST",
        "/v1/auth/bootstrap",
        "/v2/auth/bootstrap",
        "Bootstrap self-hosted access",
        ("auth",),
    ),
    (
        authentication.router,
        "POST",
        "/v1/auth/testers",
        "/v2/auth/testers",
        "Create tester access",
        ("auth",),
    ),
    (
        authentication.router,
        "GET",
        "/v1/auth/me",
        "/v2/auth/me",
        "Get current identity",
        ("auth",),
    ),
    (
        authentication.router,
        "POST",
        "/v1/auth/api-keys",
        "/v2/auth/api-keys",
        "Create API key",
        ("auth",),
    ),
    (
        authentication.router,
        "GET",
        "/v1/auth/api-keys",
        "/v2/auth/api-keys",
        "List API keys",
        ("auth",),
    ),
    (
        authentication.router,
        "DELETE",
        "/v1/auth/api-keys/{key_id}",
        "/v2/auth/api-keys/{key_id}",
        "Revoke API key",
        ("auth",),
    ),
    (
        authentication.router,
        "POST",
        "/v1/auth/api-keys/{key_id}/rotate",
        "/v2/auth/api-keys/{key_id}/rotate",
        "Rotate API key",
        ("auth",),
    ),
    (
        spaces.router,
        "GET",
        "/v1/spaces",
        "/v2/spaces",
        "List research spaces",
        ("spaces",),
    ),
    (
        spaces.router,
        "POST",
        "/v1/spaces",
        "/v2/spaces",
        "Create research space",
        ("spaces",),
    ),
    (
        spaces.router,
        "PATCH",
        "/v1/spaces/{space_id}/settings",
        "/v2/spaces/{space_id}/settings",
        "Update research-space settings",
        ("spaces",),
    ),
    (
        spaces.router,
        "PUT",
        "/v1/spaces/default",
        "/v2/spaces/default",
        "Get or create default research space",
        ("spaces",),
    ),
    (
        spaces.router,
        "DELETE",
        "/v1/spaces/{space_id}",
        "/v2/spaces/{space_id}",
        "Archive research space",
        ("spaces",),
    ),
    (
        spaces.router,
        "GET",
        "/v1/spaces/{space_id}/members",
        "/v2/spaces/{space_id}/members",
        "List research-space members",
        ("spaces",),
    ),
    (
        spaces.router,
        "POST",
        "/v1/spaces/{space_id}/members",
        "/v2/spaces/{space_id}/members",
        "Add research-space member",
        ("spaces",),
    ),
    (
        spaces.router,
        "DELETE",
        "/v1/spaces/{space_id}/members/{user_id}",
        "/v2/spaces/{space_id}/members/{user_id}",
        "Remove research-space member",
        ("spaces",),
    ),
    # Evidence input and source discovery.
    (
        documents.router,
        "GET",
        "/v1/spaces/{space_id}/documents",
        "/v2/spaces/{space_id}/documents",
        "List documents",
        ("documents",),
    ),
    (
        documents.router,
        "GET",
        "/v1/spaces/{space_id}/documents/{document_id}",
        "/v2/spaces/{space_id}/documents/{document_id}",
        "Get document",
        ("documents",),
    ),
    (
        documents.router,
        "POST",
        "/v1/spaces/{space_id}/documents/text",
        "/v2/spaces/{space_id}/documents/text",
        "Add text document",
        ("documents",),
    ),
    (
        documents.router,
        "POST",
        "/v1/spaces/{space_id}/documents/pdf",
        "/v2/spaces/{space_id}/documents/pdf",
        "Upload PDF document",
        ("documents",),
    ),
    (
        documents.router,
        "POST",
        "/v1/spaces/{space_id}/documents/{document_id}/extract",
        "/v2/spaces/{space_id}/documents/{document_id}/extraction",
        "Extract evidence from document",
        ("documents",),
    ),
    (
        marrvel.router,
        "POST",
        "/v1/spaces/{space_id}/marrvel/ingest",
        "/v2/spaces/{space_id}/sources/marrvel/ingestion",
        "Ingest MARRVEL evidence",
        ("sources",),
    ),
    # Product workflow surfaces.
    (
        research_state.router,
        "GET",
        "/v1/spaces/{space_id}/research-state",
        "/v2/spaces/{space_id}/research-state",
        "Get research state",
        ("research",),
    ),
    (
        review_queue.router,
        "GET",
        "/v1/spaces/{space_id}/review-queue",
        "/v2/spaces/{space_id}/review-items",
        "List items needing review",
        ("review",),
    ),
    (
        review_queue.router,
        "GET",
        "/v1/spaces/{space_id}/review-queue/{item_id}",
        "/v2/spaces/{space_id}/review-items/{item_id}",
        "Get review item",
        ("review",),
    ),
    (
        review_queue.router,
        "POST",
        "/v1/spaces/{space_id}/review-queue/{item_id}/actions",
        "/v2/spaces/{space_id}/review-items/{item_id}/decision",
        "Decide review item",
        ("review",),
    ),
    (
        proposals.router,
        "GET",
        "/v1/spaces/{space_id}/proposals",
        "/v2/spaces/{space_id}/proposed-updates",
        "List proposed updates",
        ("review",),
    ),
    (
        proposals.router,
        "GET",
        "/v1/spaces/{space_id}/proposals/{proposal_id}",
        "/v2/spaces/{space_id}/proposed-updates/{proposal_id}",
        "Get proposed update",
        ("review",),
    ),
    (
        proposals.router,
        "POST",
        "/v1/spaces/{space_id}/proposals/{proposal_id}/promote",
        "/v2/spaces/{space_id}/proposed-updates/{proposal_id}/promote",
        "Promote proposed update",
        ("review",),
    ),
    (
        proposals.router,
        "POST",
        "/v1/spaces/{space_id}/proposals/{proposal_id}/reject",
        "/v2/spaces/{space_id}/proposed-updates/{proposal_id}/reject",
        "Reject proposed update",
        ("review",),
    ),
    # Generic task lifecycle.
    (
        graph_explorer.router,
        "GET",
        "/v1/spaces/{space_id}/graph-explorer/claims",
        "/v2/spaces/{space_id}/evidence-map/claims",
        "List evidence-map claims",
        ("evidence-map",),
    ),
    (
        graph_explorer.router,
        "GET",
        "/v1/spaces/{space_id}/graph-explorer/entities",
        "/v2/spaces/{space_id}/evidence-map/entities",
        "List evidence-map entities",
        ("evidence-map",),
    ),
    (
        graph_explorer.router,
        "GET",
        "/v1/spaces/{space_id}/graph-explorer/entities/{entity_id}/claims",
        "/v2/spaces/{space_id}/evidence-map/entities/{entity_id}/claims",
        "List claims for entity",
        ("evidence-map",),
    ),
    (
        graph_explorer.router,
        "GET",
        "/v1/spaces/{space_id}/graph-explorer/claims/{claim_id}/evidence",
        "/v2/spaces/{space_id}/evidence-map/claims/{claim_id}/evidence",
        "List claim evidence",
        ("evidence-map",),
    ),
    (
        graph_explorer.router,
        "POST",
        "/v1/spaces/{space_id}/graph-explorer/document",
        "/v2/spaces/{space_id}/evidence-map/export",
        "Export evidence map",
        ("evidence-map",),
    ),
    (
        chat.router,
        "GET",
        "/v1/spaces/{space_id}/chat-sessions",
        "/v2/spaces/{space_id}/chat-sessions",
        "List chat sessions",
        ("chat",),
    ),
    (
        chat.router,
        "POST",
        "/v1/spaces/{space_id}/chat-sessions",
        "/v2/spaces/{space_id}/chat-sessions",
        "Create chat session",
        ("chat",),
    ),
    (
        chat.router,
        "GET",
        "/v1/spaces/{space_id}/chat-sessions/{session_id}",
        "/v2/spaces/{space_id}/chat-sessions/{session_id}",
        "Get chat session",
        ("chat",),
    ),
    (
        chat.router,
        "POST",
        "/v1/spaces/{space_id}/chat-sessions/{session_id}/messages",
        "/v2/spaces/{space_id}/chat-sessions/{session_id}/messages",
        "Send chat message",
        ("chat",),
    ),
    (
        chat.router,
        "POST",
        "/v1/spaces/{space_id}/chat-sessions/{session_id}/proposals/graph-write",
        "/v2/spaces/{space_id}/chat-sessions/{session_id}/suggested-updates",
        "Stage suggested updates from chat",
        ("chat",),
    ),
    (
        chat.router,
        "POST",
        "/v1/spaces/{space_id}/chat-sessions/{session_id}/graph-write-candidates/{candidate_index}/review",
        "/v2/spaces/{space_id}/chat-sessions/{session_id}/suggested-updates/{candidate_index}/decision",
        "Decide suggested chat update",
        ("chat",),
    ),
    # Workflow-specific task creation.
    (
        graph_search_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/graph-search/runs",
        "/v2/spaces/{space_id}/workflows/evidence-search/tasks",
        "Start evidence search task",
        ("workflows",),
    ),
    (
        graph_connection_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/graph-connections/runs",
        "/v2/spaces/{space_id}/workflows/connection-discovery/tasks",
        "Start connection discovery task",
        ("workflows",),
    ),
    (
        hypothesis_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/hypotheses/runs",
        "/v2/spaces/{space_id}/workflows/hypothesis-discovery/tasks",
        "Start hypothesis discovery task",
        ("workflows",),
    ),
    (
        mechanism_discovery_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/mechanism-discovery/runs",
        "/v2/spaces/{space_id}/workflows/mechanism-discovery/tasks",
        "Start mechanism discovery task",
        ("workflows",),
    ),
    (
        continuous_learning_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/continuous-learning/runs",
        "/v2/spaces/{space_id}/workflows/continuous-review/tasks",
        "Start continuous review task",
        ("workflows",),
    ),
    (
        full_ai_orchestrator_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/full-ai-orchestrator/runs",
        "/v2/spaces/{space_id}/workflows/autopilot/tasks",
        "Start autopilot task",
        ("workflows",),
    ),
    (
        research_onboarding_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/research-onboarding/runs",
        "/v2/spaces/{space_id}/workflows/research-onboarding/tasks",
        "Start research onboarding task",
        ("workflows",),
    ),
    (
        research_onboarding_runs.router,
        "POST",
        "/v1/spaces/{space_id}/agents/research-onboarding/turns",
        "/v2/spaces/{space_id}/workflows/research-onboarding/turns",
        "Continue research onboarding",
        ("workflows",),
    ),
    (
        supervisor_runs.router,
        "GET",
        "/v1/spaces/{space_id}/agents/supervisor/dashboard",
        "/v2/spaces/{space_id}/workflows/full-research/dashboard",
        "Get full research dashboard",
        ("workflows",),
    ),
    (
        supervisor_runs.router,
        "GET",
        "/v1/spaces/{space_id}/agents/supervisor/runs",
        "/v2/spaces/{space_id}/workflows/full-research/tasks",
        "List full research tasks",
        ("workflows",),
    ),
    # Automation and templates.
    (
        schedules.router,
        "GET",
        "/v1/spaces/{space_id}/schedules",
        "/v2/spaces/{space_id}/schedules",
        "List schedules",
        ("schedules",),
    ),
    (
        schedules.router,
        "POST",
        "/v1/spaces/{space_id}/schedules",
        "/v2/spaces/{space_id}/schedules",
        "Create schedule",
        ("schedules",),
    ),
    (
        schedules.router,
        "GET",
        "/v1/spaces/{space_id}/schedules/{schedule_id}",
        "/v2/spaces/{space_id}/schedules/{schedule_id}",
        "Get schedule",
        ("schedules",),
    ),
    (
        schedules.router,
        "PATCH",
        "/v1/spaces/{space_id}/schedules/{schedule_id}",
        "/v2/spaces/{space_id}/schedules/{schedule_id}",
        "Update schedule",
        ("schedules",),
    ),
    (
        schedules.router,
        "POST",
        "/v1/spaces/{space_id}/schedules/{schedule_id}/pause",
        "/v2/spaces/{space_id}/schedules/{schedule_id}/pause",
        "Pause schedule",
        ("schedules",),
    ),
    (
        schedules.router,
        "POST",
        "/v1/spaces/{space_id}/schedules/{schedule_id}/resume",
        "/v2/spaces/{space_id}/schedules/{schedule_id}/resume",
        "Resume schedule",
        ("schedules",),
    ),
    (
        schedules.router,
        "POST",
        "/v1/spaces/{space_id}/schedules/{schedule_id}/run-now",
        "/v2/spaces/{space_id}/schedules/{schedule_id}/start-now",
        "Start scheduled task now",
        ("schedules",),
    ),
)



def register_v2_public_aliases(router: APIRouter) -> None:
    """Register stable v2 route aliases for existing v1 route handlers."""
    for (
        source_router,
        method,
        source_path,
        target_path,
        summary,
        tags,
    ) in _ALIASES:
        _add_alias(
            target_router=router,
            source_router=source_router,
            source_path=source_path,
            target_path=target_path,
            method=method,
            summary=summary,
            tags=tags,
        )


__all__ = ["_ALIASES", "_find_route", "register_v2_public_aliases"]
